-- Preproductie: uitsluitend testgegevens.
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(trim(message)) between 1 and 2000),
  app_version text,
  status text not null default 'Ontvangen',
  reactie text,
  resolved_in_version text,
  resolved_at timestamptz,
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.comments enable row level security;
drop policy if exists comments_public_read on public.comments;
create policy comments_public_read on public.comments for select using (true);
drop policy if exists comments_public_insert on public.comments;
create policy comments_public_insert on public.comments for insert with check (char_length(trim(message)) between 1 and 2000);

create table if not exists public.releases (
  version text primary key,
  release_kind text not null check (release_kind in ('groot', 'klein')),
  published_at timestamptz not null default now(),
  notes jsonb not null default '[]'::jsonb,
  commit_sha text,
  pages_url text
);
alter table public.releases enable row level security;
drop policy if exists releases_public_read on public.releases;
create policy releases_public_read on public.releases for select using (true);
-- Algemene statussen.  Elke tabel krijgt een eigen set via table_name.
create table if not exists public.statuses (
  id bigint generated by default as identity primary key,
  table_name text not null,
  code text not null,
  status text not null,
  description text,
  color text,
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (table_name, code),
  unique (table_name, status),
  unique (table_name, id)
);

insert into public.statuses (table_name, code, status, description, color, sort_order)
values
  ('comments', 'ontvangen', 'Ontvangen', 'De opmerking is ontvangen en wacht op beoordeling.', '#2563eb', 10),
  ('comments', 'in_onderzoek', 'In onderzoek', 'De opmerking wordt onderzocht.', '#f59e0b', 20),
  ('comments', 'geaccepteerd', 'Geaccepteerd', 'De wijziging is geaccepteerd voor uitvoering.', '#86efac', 30),
  ('comments', 'doorgevoerd', 'Doorgevoerd', 'De wijziging is opgenomen in een versie.', '#15803d', 40),
  ('comments', 'niet_geaccepteerd', 'Niet geaccepteerd', 'De wijziging wordt niet uitgevoerd.', '#dc2626', 50)
on conflict (table_name, code) do update set
  status = excluded.status,
  description = excluded.description,
  color = excluded.color,
  sort_order = excluded.sort_order,
  updated_at = now();

create or replace function public.default_comment_status()
returns bigint language sql stable as $$
  select id from public.statuses
  where table_name = 'comments' and code = 'ontvangen'
  limit 1;
$$;

alter table public.comments
  add column if not exists status_scope text not null default 'comments',
  add column if not exists status_id bigint;

update public.comments c
set status_id = s.id
from public.statuses s
where s.table_name = 'comments'
  and s.status = c.status
  and c.status_id is null;

alter table public.comments
  alter column status_id set default public.default_comment_status(),
  alter column status_id set not null;

-- De oude tekstcontrole zou nieuwe statuswaarden buiten deze opzoektabel blokkeren.
alter table public.comments drop constraint if exists comments_status_check;

alter table public.comments drop constraint if exists comments_status_lookup_fkey;
alter table public.comments add constraint comments_status_lookup_fkey
  foreign key (status_scope, status_id)
  references public.statuses (table_name, id);

create or replace function public.sync_comment_status()
returns trigger language plpgsql as $$
begin
  select status into new.status
  from public.statuses
  where id = new.status_id and table_name = new.status_scope;
  return new;
end;
$$;

drop trigger if exists comments_status_sync on public.comments;
create trigger comments_status_sync
before insert or update on public.comments
for each row execute function public.sync_comment_status();

alter table public.statuses enable row level security;
drop policy if exists status_read_active on public.statuses;
create policy status_read_active on public.statuses
for select using (is_active);

-- Versie 0.6: status voor afgehandelde opmerkingen en een betrouwbare datum daarvoor.
-- Deze status verschijnt na tien dagen in de historie van de applicatie.
update public.statuses
set code = 'geen_actie_nodig',
    status = 'Geen actie nodig',
    description = 'De opmerking is beoordeeld; verdere actie is niet nodig.',
    color = '#64748b',
    sort_order = 60,
    updated_at = now()
where table_name = 'comments'
  and (code = 'geen_actie' or status = 'Geen actie');

insert into public.statuses (table_name, code, status, description, color, sort_order)
values ('comments', 'geen_actie_nodig', 'Geen actie nodig', 'De opmerking is beoordeeld; verdere actie is niet nodig.', '#64748b', 60)
on conflict (table_name, code) do update set
  status = excluded.status,
  description = excluded.description,
  color = excluded.color,
  sort_order = excluded.sort_order,
  updated_at = now();

alter table public.comments
  add column if not exists status_changed_at timestamptz;

update public.comments
set status_changed_at = coalesce(status_changed_at, resolved_at, created_at, now())
where status_changed_at is null;

alter table public.comments
  alter column status_changed_at set default now(),
  alter column status_changed_at set not null;

create or replace function public.set_comment_status_changed_at()
returns trigger language plpgsql as $$
begin
  if tg_op = 'INSERT' or new.status_id is distinct from old.status_id then
    new.status_changed_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists comments_status_changed_at on public.comments;
create trigger comments_status_changed_at
before insert or update on public.comments
for each row execute function public.set_comment_status_changed_at();

create table if not exists public.qna (
  id bigint generated by default as identity primary key,
  rubriek text not null,
  vraag text not null unique,
  antwoord text not null,
  zichtbaar boolean not null default true,
  volgorde integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.qna enable row level security;

drop policy if exists "Zichtbare Q&A zijn openbaar leesbaar" on public.qna;
create policy "Zichtbare Q&A zijn openbaar leesbaar"
  on public.qna for select using (zichtbaar = true);

insert into public.qna (rubriek, vraag, antwoord, zichtbaar, volgorde) values
  ('Zoeken', 'Hoe zoek ik naar een onderwerp of artikel?', 'Kies eerst een regeling. Typ daarna minimaal twee tekens, een begrip of een artikelnummer. Druk op Enter of klik op Zoeken.', true, 10),
  ('Zoeken', 'Kan ik zonder zoekwoord door een regeling bladeren?', 'Ja. Open in kolom 1 een hoofdstuk, afdeling of paragraaf. Klik op een artikel om de tekst in kolom 2 te lezen.', true, 20),
  ('Zoeken', 'Wat zijn favorieten en recente zoekopdrachten?', 'Met de ster bewaart u een zoekopdracht als favoriet. Bij recente zoekopdrachten en favorieten wordt de zoekopdracht direct uitgevoerd.', true, 30),
  ('Navigatie', 'Wat betekenen de drie kolommen?', 'Kolom 1 bevat de opbouw van de regeling. Kolom 2 toont de geselecteerde tekst. Kolom 3 toont bijlagen, tabellen, begrippen en terugverwijzingen.', true, 10),
  ('Navigatie', 'Hoe ga ik terug naar een eerder bekeken tekst?', 'Gebruik de pijlen boven kolom 2. Het getal ernaast laat zien op welke plaats u zich in de klikgeschiedenis bevindt. Reset leegt kolom 2 en 3 en gaat terug naar de beginregeling.', true, 20),
  ('Navigatie', 'Wat doet Klap alles in?', 'Hiermee vouwt de navigatie terug tot hoofdstukniveau. De kleinere tekst onder een ingeklapt onderdeel geeft een vooruitblik op de inhoud.', true, 30),
  ('Tekst en verwijzingen', 'Waarom zijn woorden blauw?', 'Blauwe tekst is een juridische verwijzing. Een verwijzing binnen de zes opgenomen regelingen opent in kolom 2. Aanpalende Nederlandse regelgeving opent in een apart tabblad op Wetten.nl. Europese regelgeving opent in een apart tabblad op EUR-Lex. In die externe tabbladen zijn geen aanvullende zoekfuncties van Omgevingswet Zoeker beschikbaar.', true, 10),
  ('Tekst en verwijzingen', 'Waarom zie ik soms een tabel of bijlage in kolom 3?', 'Een artikel kan verwijzen naar een tabel, bijlage of begripsbepaling. Die verschijnt dan naast de tekst, zodat het oorspronkelijke artikel zichtbaar blijft.', true, 20),
  ('Tekst en verwijzingen', 'Wat betekenen terugverwijzingen?', 'Kolom 3 kan laten zien welke artikelen uit de andere opgenomen regelingen naar het geselecteerde artikel verwijzen. Zo wordt zichtbaar waar een bepaling elders doorwerkt.', true, 30),
  ('Actualiteit', 'Hoe actueel zijn de regelingen?', 'De website bouwt dagelijks opnieuw met de officiële KOOP/BWB-bronnen. Alleen wanneer de inhoud verandert, wordt een nieuwe versie gepubliceerd. De teksten zijn actueel op de dag van de laatste geslaagde import. [[VERSIES]]', true, 10),
  ('Actualiteit', 'Blijft de website werken wanneer de Wettenbank niet bereikbaar is?', 'Ja. De gepubliceerde Omgevingswet Zoeker bevat een eigen, statische kopie van de zes opgenomen regelingen. Zoeken, navigeren en lezen blijven daarom werken. Alleen een dagelijkse actualisatie kan dan niet worden uitgevoerd. De website blijft in dat geval de laatst succesvol gepubliceerde versie tonen. Ook externe verwijzingen naar Wetten.nl zijn tijdelijk niet beschikbaar zolang die website niet bereikbaar is. [[VERSIES]]', true, 20),
  ('Actualiteit', 'Wat is de officiële bron?', 'De bron is steeds de officiële KOOP/BWB-tekst. Controleer bij formeel juridisch gebruik altijd ook de officiële publicatie en de geldende datum.', true, 30)
on conflict (vraag) do update set
  rubriek = excluded.rubriek,
  antwoord = excluded.antwoord,
  zichtbaar = excluded.zichtbaar,
  volgorde = excluded.volgorde,
  updated_at = now();


-- Bezoekstatistiek
-- Anonieme bezoekstatistiek voor Omgevingswet Zoeker.
-- Slaat geen naam, IP-adres, zoekopdracht of andere inhoudelijke gegevens op.

create table if not exists public.site_visits (
  session_id uuid primary key,
  visitor_id uuid not null,
  visited_at timestamptz not null default now()
);

create index if not exists site_visits_visited_at_idx on public.site_visits (visited_at desc);
create index if not exists site_visits_visitor_id_idx on public.site_visits (visitor_id);

alter table public.site_visits enable row level security;

create or replace function public.register_site_visit(p_session_id uuid, p_visitor_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.site_visits (session_id, visitor_id)
  values (p_session_id, p_visitor_id)
  on conflict (session_id) do nothing;
end;
$$;

revoke all on public.site_visits from anon, authenticated;
revoke all on function public.register_site_visit(uuid, uuid) from public;
grant execute on function public.register_site_visit(uuid, uuid) to anon, authenticated;

create or replace view public.site_visit_weekly as
select
  date_trunc('week', visited_at at time zone 'Europe/Amsterdam')::date as periode_start,
  count(*)::integer as bezoeken,
  count(distinct visitor_id)::integer as unieke_bezoeken
from public.site_visits
group by 1
order by 1 desc;

create or replace view public.site_visit_monthly as
select
  date_trunc('month', visited_at at time zone 'Europe/Amsterdam')::date as periode_start,
  count(*)::integer as bezoeken,
  count(distinct visitor_id)::integer as unieke_bezoeken
from public.site_visits
group by 1
order by 1 desc;
