'use strict';
(() => {
const VERSION='1.01l';
const SUPABASE_URL='https://lemcbncvqcsffatsxpdq.supabase.co';
const SUPABASE_KEY='sb_publishable_xvnpAGVE1Kf3DhO0PDck7g_ck1nix2O';
const REGS=[
 {id:'OW',name:'Omgevingswet',bwb:'BWBR0037885',file:'ow_legal_graph.json'},
 {id:'BAL',name:'Besluit activiteiten leefomgeving (BAL)',bwb:'BWBR0041330',file:'bal_legal_graph.json'},
 {id:'BBL',name:'Besluit bouwwerken leefomgeving (BBL)',bwb:'BWBR0041297',file:'bbl_legal_graph.json'},
 {id:'BKL',name:'Besluit kwaliteit leefomgeving (BKL)',bwb:'BWBR0041313',file:'bkl_legal_graph.json'},
 {id:'OB',name:'Omgevingsbesluit (OB)',bwb:'BWBR0041278',file:'ob_legal_graph.json'},
 {id:'OR',name:'Omgevingsregeling (OR)',bwb:'BWBR0045528',file:'or_legal_graph.json'}
];
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const type=n=>String(n?.type||'').toLowerCase();
const nid=n=>String(n?.id||'');
const num=n=>String(n?.number_display||n?.number||'').trim();
const parentId=n=>String(n?.parent||'');
const state={graphs:new Map(),indexes:new Map(),externalRefs:new Map(),backReferences:new Map(),registerLinks:new Map(),versions:{},norms:new Map(),normPattern:null,regulation:'BAL',glossaryRegulation:'BAL',search:{query:'',results:[],active:false},searchBusy:false,navigation:{selected:null,expanded:new Set()},viewer:{node:null,trail:[],regulation:'BAL'},side:{article:null,selected:null,reference:null,norm:null},historyTab:'recent'};
const logQueue=[];let logTimer=null;
function log(event,data={}){const e={time:new Date().toISOString(),version:VERSION,event,...data};logQueue.push(e);if(logQueue.length>500)logQueue.splice(0,logQueue.length-500);if(!logTimer)logTimer=setTimeout(flushLog,300)}
async function flushLog(){logTimer=null;if(!logQueue.length)return;const entries=logQueue.splice(0,100);try{await fetch('/ui-log',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session:'v550-'+location.search,entries})})}catch(_){}}
function regName(id){return REGS.find(r=>r.id===id)?.name||id}
function validRegulation(value,fallback='BAL'){const id=String(value||'').trim().toUpperCase();return REGS.some(r=>r.id===id)?id:fallback}
function graph(reg=state.regulation){return state.graphs.get(reg)}
function index(reg=state.regulation){return state.indexes.get(reg)}
function node(id,reg=(state.viewer.regulation||state.regulation)){return index(reg)?.byId.get(String(id))||null}
function children(n){return (n?.children||[]).map(id=>node(id,n.regId)).filter(Boolean)}
function parent(n){return n?node(parentId(n),n.regId):null}
function ancestors(n){const out=[];const seen=new Set();let cur=n;while(cur&&!seen.has(nid(cur))){seen.add(nid(cur));out.unshift(cur);cur=parent(cur)}return out}
function articleOf(n){let cur=n;const seen=new Set();while(cur&&!seen.has(nid(cur))){seen.add(nid(cur));if(type(cur)==='article')return cur;cur=parent(cur)}return null}
function legalPrefix(n){return ({chapter:'Hoofdstuk',section:'Afdeling',paragraph:'Paragraaf',subparagraph:'Paragraaf',article:'Artikel',member:'',paragraph_member:'',item:'',subitem:'',table:'Tabel',appendix:'Bijlage'})[type(n)]||''}
function label(n){if(!n)return'';return [legalPrefix(n),num(n),String(n.title||'').trim()].filter(Boolean).join(' ').trim()||String(n.title||n.id||'Element')}
function ownText(n){return String(n?.text||'').trim()}
function searchText(n){return String(n?.search_text_exact||[num(n),n?.title,ownText(n)].filter(Boolean).join(' '))}
function normalizeSearchWord(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('nl-NL')}
const SEARCH_STOPWORDS=new Set(['aan','als','bij','de','den','der','des','dit','door','een','en','het','in','met','naar','of','om','onder','op','over','te','ten','ter','tot','van','voor','waar','welke','wordt','zijn']);
function searchTerms(query){return (normalizeSearchWord(query).match(/\d+(?:\.\d+)+[\p{L}]{0,1}|[\p{L}]{2,}/gu)||[]).filter(term=>/^\d/.test(term)||!SEARCH_STOPWORDS.has(term))}
function searchWords(text){const normalized=normalizeSearchWord(text),words=[];for(const match of normalized.matchAll(/\d+(?:\.\d+)+[\p{L}]{0,1}|[\p{L}]{2,}/gu))words.push({text:match[0],index:match.index??0});return words}
function matchingSearchWords(term,words){return words.filter(word=>word.text===term)}
function buildIndex(reg,g){const byId=new Map(),byLegal=new Map();for(const n of g.nodes||[]){n.regId=reg;byId.set(nid(n),n)}
 const add=(k,n)=>{if(k&&!byLegal.has(k))byLegal.set(k,n)};
 for(const n of byId.values()){const no=normNum(num(n));if(!no)continue;const t=type(n);add(t+':'+no,n);if(t==='subparagraph')add('paragraph:'+no,n)}
 // BWB-tabellen hebben doorgaans geen eigen nummer. Een verwijzing als
 // "tabel 4.36" duidt dan op de tabel die bij artikel 4.36 hoort.
 for(const n of byId.values()){if(type(n)!=='table'||!n.article_id)continue;const article=byId.get(String(n.article_id)),articleNo=normNum(num(article));if(articleNo)add('table:'+articleNo,n)}
 const glossary=(Array.isArray(g.glossary)?g.glossary:[]).filter(x=>x&&x.term&&x.definition).sort((a,b)=>String(b.term).length-String(a.term).length);
 const glossaryByKey=new Map(glossary.map(x=>[String(x.key||x.term_normalized||x.term),x])); state.indexes.set(reg,{byId,byLegal,glossary,glossaryByKey});}
function buildRegisterIndex(){
 const bkl=graph('BKL'),links=new Map();if(!bkl)return;
 const byId=index('BKL')?.byId,appendix=(bkl.nodes||[]).find(n=>type(n)==='appendix'&&normNum(num(n))==='vii');
 if(!appendix||!byId)return;
 const todo=[nid(appendix)],seen=new Set();
 while(todo.length){const id=todo.pop();if(seen.has(id))continue;seen.add(id);const n=byId.get(id);if(!n)continue;todo.push(...(n.children||[]));for(const ref of n.external_refs||[]){if(ref?.bwb_id!=='BWBR0041330'||String(ref?.target?.type||'')!=='article')continue;const target=index('BAL')?.byLegal.get('article:'+normNum(ref.target.number));if(target)links.set(nid(target),{source:'Bijlage VII Bkl',article:target});}}
 state.registerLinks=links;
}
function registerNotices(article){if(!article||article.regId!=='BAL')return[];const hit=state.registerLinks.get(nid(article));return hit?[hit]:[]}
function renderRegisterNotices(article){const notices=registerNotices(article);if(!notices.length)return'';return notices.map(n=>`<section class="registerNotice"><div class="registerNoticeLabel">Gekoppeld register</div><h3>Register externe veiligheidsrisico’s</h3><p>Deze activiteit kan in aanmerking komen voor opname in het Register externe veiligheidsrisico’s (REV).</p><p>Registratie van de activiteit hangt af van de locatiespecifieke gegevens uit de melding of vergunningaanvraag.</p><div class="registerNoticeSource">Juridische koppeling: ${esc(n.source)}.</div></section>`).join('')}
function normNum(s){return String(s??'').replace(/\s+/g,'').replace(/[.)]$/,'').toLowerCase()}
function normKey(s){return String(s??'').replace(/\s+/g,' ').trim().toLocaleLowerCase('nl-NL')}
function escapeRegExp(s){return String(s).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function buildNormIndex(){const catalog=(graph('OR')?.nodes||[]).find(n=>type(n)==='appendix'&&normNum(num(n))==='ii'&&/uitgaven en verwijzingen/i.test(String(n.title||''))),table=(catalog?.source_tree||[]).find(x=>x?.kind==='table');state.norms=new Map();state.normPattern=null;if(!catalog||!table||!Array.isArray(table.rows)||table.rows.length<2)return;const headers=(table.rows[0]||[]).map(c=>String(c?.text||'').trim());for(const row of table.rows.slice(1)){const cells=(row||[]).map(c=>String(c?.text||'').trim()),key=normKey(cells[0]);if(key&&!state.norms.has(key))state.norms.set(key,{key,norm:cells[0],headers,cells,appendix:catalog})}const terms=[...state.norms.values()].map(x=>x.norm).filter(Boolean).sort((a,b)=>b.length-a.length).map(escapeRegExp);if(terms.length)state.normPattern=new RegExp('(^|[^\\p{L}\\p{N}])('+terms.join('|')+')(?=$|[^\\p{L}\\p{N}])','giu');log('NORM_CATALOG_LOADED',{count:state.norms.size})}
function isNormCatalogSource(source){let cur=source,seen=new Set();while(cur&&!seen.has(nid(cur))){seen.add(nid(cur));if(cur.regId==='OR'&&type(cur)==='appendix'&&normNum(num(cur))==='ii'&&/uitgaven en verwijzingen/i.test(String(cur.title||'')))return true;cur=parent(cur)}return false}
function roots(reg){return [...(index(reg)?.byId.values()||[])].filter(n=>!parentId(n)&&['chapter','appendix'].includes(type(n)))}
function navChildren(n){if(type(n)==='article')return[];return children(n).filter(x=>['chapter','section','paragraph','subparagraph','article'].includes(type(x)))}
function legalChildren(n){return children(n).filter(x=>!['table','appendix'].includes(type(x)))}
function articleAttachments(ar){if(!ar)return[];const ids=Array.isArray(ar.article_attachments)?ar.article_attachments:[];return ids.map(id=>node(id,ar.regId)).filter(x=>['table','appendix'].includes(type(x))).filter(x=>x.display_mode!=='inline')}
function contextualTableAttachments(article){
 if(!article)return[];let scope=parent(article);while(scope&&!['paragraph','subparagraph'].includes(type(scope)))scope=parent(scope);if(!scope)return[];
 const articles=children(scope).filter(n=>type(n)==='article'),at=articles.findIndex(n=>nid(n)===nid(article));if(at<=0)return[];
 const source=articles[0],direct=articleAttachments(source).filter(n=>type(n)==='table');
 return direct.map(attachment=>({source,attachment}));
}
function isReliableAttachment(a){return Boolean(a?.article_id)}
function resultArticle(n){return articleOf(n)||n}
function stripResultMetadata(n,text){let s=String(text||'').replace(/\s+/g,' ').trim();const variants=[[num(n),String(n?.title||'').trim()].filter(Boolean).join(' '),label(n)].filter(Boolean);for(let pass=0;pass<3;pass++){let changed=false;for(const v of variants){if(s.toLocaleLowerCase('nl-NL').startsWith(v.toLocaleLowerCase('nl-NL'))){s=s.slice(v.length).trim().replace(/^[\s|:;–—-]+/,'');changed=true;}}if(!changed)break;}return s} 
function resultSource(r){return stripResultMetadata(r.match,r.source)}
function snippet(text,q,max=260){text=String(text||'').replace(/\s+/g,' ').trim();const low=text.toLowerCase(),needle=q.toLowerCase(),i=low.indexOf(needle);if(i<0)return text.slice(0,max);const start=Math.max(0,i-90),end=Math.min(text.length,i+needle.length+150);return (start?'…':'')+text.slice(start,end)+(end<text.length?'…':'')}
function highlight(s,q){const safe=esc(s);if(!q)return safe;const re=new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'gi');return safe.replace(re,m=>'<mark>'+m+'</mark>')}
const LEGAL_ORDER={chapter:0,section:1,paragraph:2,subparagraph:3,article:4,member:5,paragraph_member:5,item:6,subitem:7,table:8,appendix:9};
function compareLegalPath(a,b){const aa=ancestors(a),bb=ancestors(b),len=Math.min(aa.length,bb.length);for(let i=0;i<len;i++){const at=type(aa[i]),bt=type(bb[i]),kind=(LEGAL_ORDER[at]??99)-(LEGAL_ORDER[bt]??99);if(kind)return kind;const number=num(aa[i]).localeCompare(num(bb[i]),'nl',{numeric:true,sensitivity:'base'});if(number)return number;const title=label(aa[i]).localeCompare(label(bb[i]),'nl',{numeric:true,sensitivity:'base'});if(title)return title}return aa.length-bb.length}
function searchPostingKey(term){return /^\d/.test(term)?'number:'+term:'word:'+term}
function prepareSearchIndex(reg=state.regulation){const idx=index(reg),g=graph(reg);if(!idx||!g)return null;if(idx.searchIndex)return idx.searchIndex;for(const [id,cached] of state.indexes)if(id!==reg)delete cached.searchIndex;const postings=new Map();for(const n of g.nodes||[]){const source=searchText(n),words=searchWords(source),keys=new Set(words.map(word=>searchPostingKey(word.text)));const entry={node:n,source,haystack:normalizeSearchWord(source),words};for(const key of keys){let rows=postings.get(key);if(!rows)postings.set(key,rows=new Set());rows.add(entry)}}return idx.searchIndex={postings}}
function search(q){q=q.trim();const terms=searchTerms(q),phrase=normalizeSearchWord(q);if(q.length<2||!terms.length)return[];const prepared=prepareSearchIndex();if(!prepared)return[];const groups=terms.map(term=>prepared.postings.get(searchPostingKey(term)));if(groups.some(group=>!group?.size))return[];groups.sort((a,b)=>a.size-b.size);let candidates=[...groups[0]];for(const group of groups.slice(1))candidates=candidates.filter(entry=>group.has(entry));const found=new Map();for(const entry of candidates){const {node:n,source,haystack,words}=entry,matches=terms.map(term=>matchingSearchWords(term,words));if(matches.some(match=>!match.length))continue;const positions=matches.map(match=>match[0].index),spread=Math.max(...positions)-Math.min(...positions),score=(haystack.includes(phrase)?100000:0)+Math.max(0,1000-spread);const r=resultArticle(n),key=nid(r),current=found.get(key),item={node:r,match:n,source,hits:1,score};if(!current)found.set(key,item);else{current.hits++;if(score>current.score||(score===current.score&&nid(n)===nid(r)&&nid(current.match)!==nid(r))){current.match=n;current.source=source;current.score=score}}}return [...found.values()].sort((a,b)=>b.score-a.score||compareLegalPath(a.node,b.node)||compareLegalPath(a.match,b.match)||label(a.match).localeCompare(label(b.match),'nl',{numeric:true,sensitivity:'base'}))}
function saveHistory(q){const lim=Math.max(1,Number(localStorage.getItem('owz_history_limit')||10));let a=history().filter(x=>!(x.query===q&&x.reg===state.regulation));a.unshift({query:q,reg:state.regulation,label:`${q} — ${state.regulation}`});localStorage.setItem('owz_history',JSON.stringify(a.slice(0,lim)))}
function history(){try{return JSON.parse(localStorage.getItem('owz_history')||'[]')}catch(_){return[]}}
function favorites(){try{return JSON.parse(localStorage.getItem('owz_favorites')||'[]')}catch(_){return[]}}
function queryFavorite(q=String($('searchInput').value||'').trim()){return favorites().some(x=>x.kind!=='result'&&x.query===q&&x.reg===state.regulation)}
function toggleQueryFavorite(){const q=String($('searchInput').value||'').trim();if(q.length<2)return;let a=favorites();const i=a.findIndex(x=>x.query===q&&x.reg===state.regulation);if(i>=0)a.splice(i,1);else a.unshift({query:q,reg:state.regulation,label:`${q} — ${state.regulation}`});localStorage.setItem('owz_favorites',JSON.stringify(a));updateStar();if(!historyPanelHidden())renderHistory()}
function resultFavorite(r){return favorites().some(x=>x.kind==='result'&&x.nodeId===nid(r.node)&&x.reg===state.regulation)}
function toggleResultFavorite(index){const r=state.search.results[index];if(!r)return;let a=favorites();const i=a.findIndex(x=>x.kind==='result'&&x.nodeId===nid(r.node)&&x.reg===state.regulation);if(i>=0)a.splice(i,1);else a.unshift({kind:'result',nodeId:nid(r.node),reg:state.regulation,label:`${label(r.node)} — ${regName(state.regulation)}`});localStorage.setItem('owz_favorites',JSON.stringify(a));renderSearchResults();if(state.historyTab==='favorites'&&!historyPanelHidden())renderHistory();setStatus(i>=0?`Favoriet verwijderd: ${label(r.node)}.`:`Favoriet bewaard: ${label(r.node)}.`)}
function historyPanelHidden(){return $('historyPanel').hidden}
function updateStar(){$('favoriteQueryButton').textContent=queryFavorite()?'★':'☆'}
function renderHistory(){const data=state.historyTab==='favorites'?favorites():history();const box=$('historyPanel');box.innerHTML=data.slice(0,7).map((x,i)=>`<button class="historyItem" data-history="${i}">${esc(x.label||x.query||'')}</button>`).join('')||'<div class="empty">Geen items.</div>';box.hidden=false}
function closeHistory(){$('historyPanel').hidden=true}
function setStatus(s){$('status').textContent=s}
function commentHeaders(){return {'Content-Type':'application/json','apikey':SUPABASE_KEY,'Authorization':'Bearer '+SUPABASE_KEY}}
function anonymousIdentifier(storage,key){try{let value=storage.getItem(key);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value||'')){if(!globalThis.crypto?.randomUUID)return'';value=globalThis.crypto.randomUUID();storage.setItem(key,value)}return value}catch(_){return''}}
async function registerSiteVisit(){const visitorId=anonymousIdentifier(localStorage,'owz_visitor_id'),sessionId=anonymousIdentifier(sessionStorage,'owz_visit_session');if(!visitorId||!sessionId)return;try{const response=await fetch(SUPABASE_URL+'/rest/v1/rpc/register_site_visit',{method:'POST',headers:{...commentHeaders(),Prefer:'return=minimal'},body:JSON.stringify({p_session_id:sessionId,p_visitor_id:visitorId})});if(!response.ok)console.warn('Bezoekmeting kon niet worden opgeslagen.',response.status)}catch(_){console.warn('Bezoekmeting kon niet worden opgeslagen.')}}
async function submitComment(e){e.preventDefault();const message=String($('commentMessage').value||'').trim(),error=$('commentError'),submit=$('submitComment');error.textContent='';if(!message)return;submit.disabled=true;try{const res=await fetch(SUPABASE_URL+'/rest/v1/comments',{method:'POST',headers:{...commentHeaders(),Prefer:'return=minimal'},body:JSON.stringify({message,app_version:VERSION})});if(!res.ok){const detail=await res.text();throw new Error('HTTP '+res.status+(detail?': '+detail:''))}$('commentModal').close();$('commentMessage').value='';$('commentThanksModal').showModal();setStatus('Je opmerking is opgeslagen.');log('COMMENT_SUBMITTED')}catch(err){console.warn('Opmerking kon niet worden opgeslagen.',err);error.textContent='Opslaan lukt nu niet. Probeer het later opnieuw.'}finally{submit.disabled=false}}
const COMMENT_STATUS={
 'Ontvangen':'received',
 'In onderzoek':'investigating',
 'Geaccepteerd':'accepted',
 'Doorgevoerd':'implemented',
 'Niet geaccepteerd':'rejected',
 'Geen actie nodig':'noAction'
};
function commentStatus(value){return COMMENT_STATUS[value]?value:'Ontvangen'}
function isHistoricComment(row,now=Date.now()){const status=commentStatus(row.status);if(status==='Doorgevoerd'||status==='Niet geaccepteerd')return true;if(status!=='Geen actie nodig')return false;const since=new Date(row.status_changed_at||row.updated_at||row.created_at).getTime();return Number.isFinite(since)&&now-since>=10*24*60*60*1000}
function renderComment(row){const status=commentStatus(row.status),resolved=row.resolved_in_version?`<span>Opgelost in: ${esc(row.resolved_in_version)}</span>`:'',reply=String(row.reactie||'').trim(),response=`<div class="commentResponse"><strong>Reactie ontwikkelaar</strong>${reply?`<div>${esc(reply)}</div>`:''}</div>`,explanation=status==='Doorgevoerd'&&String(row.admin_note||'').trim()?`<div class="commentResolution"><strong>Toelichting:</strong> ${esc(row.admin_note)}</div>`:'';return `<article class="commentItem"><div class="commentMeta"><span>Geplaatst: ${esc(new Date(row.created_at).toLocaleString('nl-NL',{dateStyle:'long',timeStyle:'short'}))}</span><span>Versie: ${esc(row.app_version||VERSION)}</span>${resolved}<span class="commentStatus ${COMMENT_STATUS[status]}">${esc(status)}</span></div>${esc(row.message)}${response}${explanation}</article>`}
async function openComments(mode='current'){const modal=$('commentsModal'),list=$('commentsList'),historic=mode==='history';$('commentsMeta').textContent=historic?`Historie van opmerkingen bij Omgevingswet Zoeker ${VERSION}.`:`Actuele opmerkingen bij Omgevingswet Zoeker ${VERSION}.`;$('commentHistoryButton').textContent=historic?'Actuele opmerkingen':'Historie';$('commentHistoryButton').dataset.commentMode=historic?'current':'history';list.innerHTML='<div class="commentLoading">Opmerkingen laden…</div>';if(!modal.open)modal.showModal();try{const res=await fetch(SUPABASE_URL+'/rest/v1/comments?select=*&order=created_at.desc',{headers:commentHeaders()});if(!res.ok)throw new Error('HTTP '+res.status);const rows=(await res.json()).filter(row=>historic?isHistoricComment(row):!isHistoricComment(row));list.innerHTML=rows.length?rows.map(renderComment).join(''):`<div class="commentLoading">${historic?'Er staan nog geen opmerkingen in de historie.':'Er zijn geen actuele opmerkingen.'}</div>`;log('COMMENTS_LIST_OPEN',{count:rows.length,mode})}catch(_){list.innerHTML='<div class="commentLoading">De opmerkingen kunnen nu niet worden geladen.</div>'}}
function clearSide(){state.side={article:null,selected:null,reference:null};renderSide()}
function syncSideForViewer(n){if(type(n)==='article'){state.side={article:n,selected:null,reference:null};renderSide()}else clearSide()}
function clearSearch(){state.search={query:'',results:[],active:false};$('resultCount').textContent=''}
function renderNavigation(){const box=$('navigation');$('navRegulationLabel').textContent=`Zoeken in: ${regName(state.regulation)}`;const rs=roots(state.regulation);if(!rs.length){box.innerHTML='<div class="empty">Geen navigatie beschikbaar.</div>';return}box.innerHTML=rs.map(n=>renderNavNode(n,0)).join('')}
function navPreview(kids){if(!kids.length)return'';const first=kids[0],last=kids[kids.length-1],kind={section:'Afdeling',paragraph:'Paragraaf',subparagraph:'Paragraaf',article:'Artikel'}[type(first)]||'';if(!kind)return'';const start=num(first),end=num(last);if(!start)return'';const range=end&&end!==start?`${start} t/m ${end}`:start;return `<div class="navPreview" aria-label="Vooruitzicht: ${esc(kind+' '+range)}">${esc(kind+' '+range)}</div>`}
function renderNavNode(n,depth){const kids=navChildren(n),expanded=state.navigation.expanded.has(nid(n)),selected=nid(state.navigation.selected)===nid(n);return `<div class="navNode"><button class="navRow ${selected?'selected':''}" data-nav="${esc(nid(n))}"><span class="chev">${kids.length?(expanded?'⌄':'›'):'•'}</span><span>${esc(label(n))}</span></button>${expanded&&kids.length?`<div class="navChildren">${kids.map(x=>renderNavNode(x,depth+1)).join('')}</div>`:(!expanded?navPreview(kids):'')}</div>`}
function expandPath(n){state.navigation.expanded.clear();for(const x of ancestors(n))if(type(x)!=='article')state.navigation.expanded.add(nid(x))}
function rememberViewerStep(n,reset=false){const previous=Array.isArray(state.viewer.history)?state.viewer.history:[],at=Number.isInteger(state.viewer.historyIndex)?state.viewer.historyIndex:previous.length-1;const history=reset?[]:previous.slice(0,at+1);if(history[history.length-1]!==n)history.push(n);state.viewer.history=history;state.viewer.historyIndex=history.length-1}
function updateViewerHistoryControls(){const h=state.viewer.history||[],at=Number.isInteger(state.viewer.historyIndex)?state.viewer.historyIndex:-1;$('viewerBack').disabled=at<=0;$('viewerForward').disabled=at<0||at>=h.length-1;$('viewerHistoryCount').textContent=h.length?`${at+1} van ${h.length}`:'0 van 0'}function moveViewerHistory(delta){const history=state.viewer.history||[],next=(state.viewer.historyIndex??history.length-1)+delta,n=history[next];if(!n)return;state.viewer.historyIndex=next;state.viewer.node=n;state.viewer.trail=ancestors(n);state.viewer.regulation=n.regId||state.regulation;state.viewer.overview=false;clearSide();renderViewer();setStatus(`${label(n)} geopend vanuit het kruimelpad.`);log('BREADCRUMB_HISTORY',{direction:delta<0?'back':'forward',id:nid(n)})}
function selectNavigation(n){clearSearch();state.navigation.selected=n;state.viewer={node:n,trail:ancestors(n),regulation:state.regulation,history:[],historyIndex:-1};rememberViewerStep(n,true);clearSide();if(type(n)!=='article'){if(state.navigation.expanded.has(nid(n)))state.navigation.expanded.delete(nid(n));else state.navigation.expanded.add(nid(n))}renderNavigation();renderViewer();setStatus(`${label(n)} geselecteerd in navigatie.`);log('NAV_SELECT',{id:nid(n),type:type(n)})}
function renderViewer(){updateViewerHistoryControls();const box=$('viewer');if(state.search.active){renderSearchResults();return}if(state.viewer.overview){const rs=roots(state.regulation);box.innerHTML=`<div class="breadcrumb"><span>${esc(regName(state.regulation))}</span></div><div class="regulationOverview">${rs.map(n=>`<button class="overviewNode" data-view-node="${esc(nid(n))}">${esc(label(n))}</button>`).join('')||'<div class="empty">Geen hoofdstukken of bijlagen beschikbaar.</div>'}</div>`;return}const n=state.viewer.node;if(!n){box.innerHTML='<div class="empty">Selecteer een element in de navigatie of voer een zoekopdracht uit.</div>';return}const trail=state.viewer.trail;const crumb=trail.map((x,i)=>{const prefix=(i===0||trail[i-1]?.regId!==x.regId)?regName(x.regId)+' — ':'';return i===trail.length-1?`<div class="breadcrumbStep current"><span>${esc(prefix+label(x))}</span></div>`:`<div class="breadcrumbStep"><button data-crumb="${i}">${esc(prefix+label(x))}</button></div>`}).join('');box.innerHTML=`${crumb?`<div class="breadcrumb"><div class="breadcrumbPath">${crumb}</div></div>`:''}<div class="viewerContent">${renderNodeView(n)}</div>`;bindInlineLinks(box);bindTableResizers(box)}
function searchResultBreadcrumb(r){const path=ancestors(r.node).slice(0,-1).filter(n=>['chapter','section','paragraph','subparagraph'].includes(type(n)));const reg=`<button class="resultCrumb" data-result-reg="${esc(state.regulation)}">${esc(regName(state.regulation))}</button>`;const rest=path.map(n=>`<span class="crumbSep">›</span><button class="resultCrumb" data-result-crumb="${esc(nid(n))}">${esc(label(n))}</button>`).join('');return `<div class="resultBreadcrumb">${reg}${rest}</div>`}
function renderSearchResults(){const box=$('viewer'),items=state.search.results;$('resultCount').textContent=`${items.length} resultaat${items.length===1?'':'en'}`;if(!items.length){box.innerHTML='<div class="empty">Geen zoekresultaten.</div>';return}box.innerHTML=`<div class="resultList">${items.slice(0,200).map((r,i)=>`<div class="searchResult" data-result="${i}">${searchResultBreadcrumb(r)}<div class="resultTitleRow"><div class="resultTitle">${esc(label(r.node))}</div><span class="resultHitCount">${r.hits} ${r.hits===1?'treffer':'treffers'}</span><button class="resultFavorite" type="button" data-result-favorite="${i}" title="${resultFavorite(r)?'Favoriet verwijderen':'Als favoriet bewaren'}" aria-label="${resultFavorite(r)?'Favoriet verwijderen':'Als favoriet bewaren'}">${resultFavorite(r)?'★':'☆'}</button></div><div class="resultSnippet">${highlight(snippet(resultSource(r),state.search.query),state.search.query)}</div></div>`).join('')}</div>${items.length>200?`<div class="empty">Eerste 200 van ${items.length} resultaten weergegeven.</div>`:''}`}
function openSearchBreadcrumbNode(n){if(!n)return;state.search.active=false;state.viewer={node:n,trail:ancestors(n),overview:false,regulation:state.regulation,history:[],historyIndex:-1};rememberViewerStep(n,true);clearSide();renderViewer();setStatus(`${label(n)} geopend vanuit het kruimelpad van een zoekresultaat.`);log('SEARCH_BREADCRUMB_OPEN',{id:nid(n),type:type(n)})}
function openSearchRegulation(){state.search.active=false;state.viewer={node:null,trail:[],overview:true,regulation:state.regulation};clearSide();renderViewer();setStatus(`${regName(state.regulation)} geopend vanuit het kruimelpad van een zoekresultaat.`);log('SEARCH_BREADCRUMB_REGULATION',{reg:state.regulation})}
function renderNodeView(n){if(isGlossaryAppendix(n))return renderGlossaryAppendix();if(type(n)==='appendix')return renderAppendixView(n);if(type(n)==='article')return renderArticle(n);const kids=legalChildren(n);return `<div class="legalNode"><div class="legalHead">${esc(label(n))}</div>${kids.length?`<div class="legalChildren legalOverviewList">${kids.map(k=>`<div class="legalNode clickable" data-view-node="${esc(nid(k))}"><div class="legalHead legalLinkVisual">${esc(label(k))}</div></div>`).join('')}</div>`:'<div class="empty">Dit onderdeel bevat geen afzonderlijke artikelen.</div>'}</div>`}
function appendixShortTitle(a){const t=String(a?.title||'').trim();const m=t.match(/\(([^()]*)\)\s*$/);return m?m[1].replace(/^./,c=>c.toUpperCase()):''}
function appendixArticleNumbers(a){const t=String(a?.title||'');const before=t.replace(/\([^()]*\)\s*$/,'');const m=before.match(/artikelen?\s+(.+?)(?:\s+van\s+dit\s+besluit|$)/i);return m?[...m[1].matchAll(/\b\d+(?:\.\d+)+[a-z]?\b/gi)].map(x=>x[0]):[]}
function renderAppendixArticleLinks(a){const nums=appendixArticleNumbers(a);if(!nums.length)return'';return `<div class="appendixBelongs"><div class="appendixBelongsTitle">Behoort bij ${nums.length===1?'artikel':'artikelen'}</div><div class="appendixBelongsLinks appendixArticleList">${nums.map(no=>{const t=resolveRef('artikel '+no,a.regId);const title=String(t?.title||'').trim().replace(/^\((.*)\)$/,'$1');const link=t?`<button class="legalLink" data-inline="${esc(nid(t))}">${esc(no)}</button>`:`<span class="appendixArticleNumber">${esc(no)}</span>`;return `<div class="appendixArticleRow">${link}${title?`<span class="appendixArticleDescription">${esc(title)}</span>`:''}</div>`}).join('')}</div></div>`}
function appendixBlock(b){return typeof b==='object'&&b?b:{text:String(b??''),indent:0,attrs:{}}} function appendixAlignClass(b){const a=String(appendixBlock(b).attrs?.align||'').toLowerCase();return ['left','right','center','justify'].includes(a)?' appendixAlign-'+a:''} function renderAppendixLooseText(a){const raw=Array.isArray(a?.blocks)&&a.blocks.length?a.blocks:(ownText(a)?[ownText(a)]:[]);if(!raw.length)return'';const blocks=raw.map(appendixBlock);const classes=blocks.map(b=>String(b.text).match(/^\s*(S\d+)\s*:\s*(.+)$/i));if(blocks.length>1&&classes.every(Boolean)){return `<section class="appendixLooseGroup"><div class="appendixClassList">${classes.map((m,i)=>`<div class="appendixClassRow${appendixAlignClass(blocks[i])}"><strong>${esc(m[1])}</strong><span>${renderInline(a,m[2])}</span></div>`).join('')}</div></section>`}return `<div class="appendixLooseText">${blocks.map(b=>`<p class="appendixSourceParagraph${appendixAlignClass(b)}" style="--appendix-indent:${Math.max(0,Number(b.indent)||0)}">${renderInline(a,b.text)}</p>`).join('')}</div>`}
function renderPublisherValue(source,text){const site=publisherWebsite(text);if(!site)return renderInline(source,text);const raw=String(text||''),at=raw.indexOf(site.shown);return `${renderInline(source,raw.slice(0,at))}<a class="publisherLink" href="${esc(site.url)}" target="_blank" rel="noopener noreferrer" title="Opent de website van de uitgever in een nieuw tabblad">${esc(site.shown)} <span aria-hidden="true">↗</span></a>${renderInline(source,raw.slice(at+site.shown.length))}`}
function renderSourceTable(t,key='source'){const rows=Array.isArray(t.rows)?t.rows:[];const source=state.viewer.node,publisherColumn=(rows[0]||[]).findIndex(c=>/uitgever/i.test(String(c?.text||''))),minWidth=tableMinWidth(t);return `<div class="appendixSourceTableWrap"><table class="legalTable appendixSourceTable" data-resizable-table data-table-key="${esc(key)}"${minWidth?` style="min-width:${minWidth}px"`:''}>${tableColgroup(t)}<tbody>${rows.map((r,rowIndex)=>`<tr>${r.map((c,columnIndex)=>{const x=typeof c==='object'?c:{text:String(c??'')};const tag=x.header?'th':'td',cs=Number(x.colspan||1),cl=tableCellClass(x),content=rowIndex>0&&columnIndex===publisherColumn?renderPublisherValue(source,x.text||''):renderInline(source,x.text||''),handle=rowIndex===0&&columnIndex+cs<tableColumnCount(t)?`<span class="tableResizeHandle" data-table-resize="${columnIndex}" title="Sleep om de kolombreedte aan te passen" aria-hidden="true"></span>`:'';return `<${tag}${x.rowspan>1?` rowspan="${x.rowspan}"`:''}${x.colspan>1?` colspan="${x.colspan}"`:''}${cl?` class="${cl.trim()}"`:''}>${content}${handle}</${tag}>`}).join('')}</tr>`).join('')}</tbody></table></div>`}
function sourceDescendantText(x){return (x?.children||[]).map(c=>`${c?.text||''} ${sourceDescendantText(c)}`).join(' ')}
function sourceOwnText(x){const own=String(x?.text||'').replace(/\s+/g,' ').trim(),desc=sourceDescendantText(x).replace(/\s+/g,' ').trim();return own&&(!desc||!desc.toLocaleLowerCase('nl-NL').includes(own.toLocaleLowerCase('nl-NL')))?own:''}
function sourceHasMatchingHeading(x){const title=String(x?.title||'').replace(/\s+/g,' ').trim().toLocaleLowerCase('nl-NL');return !!title&&(x?.children||[]).some(c=>c?.kind==='heading'&&String(c?.title||'').replace(/\s+/g,' ').trim().toLocaleLowerCase('nl-NL')===title)}
function renderAppendixSourceNode(x,depth=0,path='0',owner=state.viewer.node){if(!x)return'';const k=x.kind||'container',own=sourceOwnText(x);if(k==='table')return renderSourceTable(x,`${owner?.regId||state.regulation}:${nid(owner)}:source:${path}`);if(k==='image'){const name=String(x.name||'').replace(/[^A-Za-z0-9._-]/g,'');const reg=String(state.viewer.node?.regId||state.regulation).toLowerCase();const alt=String(x.alt||'Officiële illustratie');return name?`<figure class="officialIllustration ${x.display==='inline'?'inline':''}"><img src="data/illustrations/${esc(reg)}/${esc(name)}" alt="${esc(alt)}"${x.width?` width="${esc(x.width)}"`:''}${x.height?` height="${esc(x.height)}"`:''} loading="lazy" onerror="this.closest('figure').hidden=true"><figcaption>${esc(alt)}</figcaption></figure>`:''}if(k==='heading'){const txt=[x.number,x.title].filter(Boolean).join(' ');return `<div class="appendixSourceHeading appendixSourceDepth${Math.min(depth,5)}">${esc(txt||x.text||'')}</div>`}if(k==='paragraph')return `<p class="appendixSourceParagraph appendixSourceDepth${Math.min(depth,5)}">${renderInline(state.viewer.node,x.text||'')}</p>`;if(k==='list_item'){const no=x.number?normalizeEnumDisplay(x.number):'';return `<div class="appendixSourceListItem appendixSourceDepth${Math.min(depth,5)}"><span class="appendixSourceEnum">${esc(no)}</span><div>${own?`<div>${renderInline(state.viewer.node,own)}</div>`:''}${(x.children||[]).map((c,i)=>renderAppendixSourceNode(c,depth+1,`${path}.${i}`,owner)).join('')}</div></div>`}const head=sourceHasMatchingHeading(x)?'':[x.number,x.title].filter(Boolean).join(' ');return `<section class="appendixSourceContainer appendixSourceDepth${Math.min(depth,5)}">${head?`<div class="appendixSourceHeading">${esc(head)}</div>`:''}${own?`<div class="appendixSourceOwnText">${renderInline(state.viewer.node,own)}</div>`:''}${(x.children||[]).map((c,i)=>renderAppendixSourceNode(c,depth+1,`${path}.${i}`,owner)).join('')}</section>`}
function normalizeEnumDisplay(v){v=String(v||'').trim();if(/^[a-z]$/i.test(v))return v.toLowerCase()+'.';return v.replace(/º/g,'°').replace(/^(\d+)\.$/,'$1')}
function renderAppendixView(a){const kids=children(a);const short=appendixShortTitle(a);const tree=Array.isArray(a.source_tree)?a.source_tree:[];const content=tree.length?tree.map((x,i)=>renderAppendixSourceNode(x,0,String(i),a)).join(''):renderAppendixLooseText(a)+kids.map((k,i)=>renderAppendixPart(k,0,i+1)).join('');return `<section class="appendixView"><header class="appendixHeader"><h2>Bijlage ${esc(num(a))}</h2>${short?`<div class="appendixSubtitle">${esc(short)}</div>`:''}</header>${renderAppendixArticleLinks(a)}<div class="appendixContent appendixSourceContent">${content}</div></section>`}
function renderAppendixPart(n,depth=0,seq=1){if(type(n)==='table')return `<div class="appendixTable">${renderAttachment(n)}</div>`;const kids=children(n);const no=num(n);const heading=label(n);const text=ownText(n);const isItem=['member','item'].includes(type(n));const cls=`appendixPart appendixDepth${Math.min(depth,4)}${isItem?' appendixEnumerated':''}`;const head=heading&&heading!==text?`<div class="appendixPartHead">${esc(heading)}</div>`:'';const body=text?`<div class="appendixPartText">${renderInline(n,text)}</div>`:'';const inner=kids.length?`<div class="appendixSubparts">${kids.map((k,i)=>renderAppendixPart(k,depth+1,i+1)).join('')}</div>`:'';if(isItem&&no)return `<div class="${cls}"><div class="appendixEnum"><span class="appendixEnumNo">${esc(no)}</span><div>${body}${inner}</div></div></div>`;return `<section class="${cls}">${head}${body}${inner}</section>`}

function inlineArticleAttachments(ar){
 if(!ar)return[];
 const ids=Array.isArray(ar.article_attachments)?ar.article_attachments:[];
 return ids.map(id=>node(id,ar.regId)).filter(x=>['table','appendix'].includes(type(x))&&x.display_mode==='inline');
}
function renderIllustrations(n){const reg=String(n?.regId||state.viewer.regulation||state.regulation).toLowerCase();return (n?.illustrations||[]).map(x=>{const name=String(x.name||'').replace(/[^A-Za-z0-9._-]/g,''),alt=String(x.alt||'Officiële illustratie');return name?`<figure class="officialIllustration ${x.display==='inline'?'inline':''}"><img src="data/illustrations/${esc(reg)}/${esc(name)}" alt="${esc(alt)}"${x.width?` width="${esc(x.width)}"`:''}${x.height?` height="${esc(x.height)}"`:''} loading="lazy" onerror="this.closest('figure').hidden=true"><figcaption>${esc(alt)}</figcaption></figure>`:''}).join('')}
function renderArticle(ar){
 const inlineAt=inlineArticleAttachments(ar);
 const inlineIds=new Set(inlineAt.map(nid));
 const bodyChildren=children(ar).map(k=>renderArticleChild(k,ar,inlineIds)).join('');
 // Niet iedere BWB-tabel hangt als direct child in de graph. article_attachments is
 // daarom de structurele bron voor de fallback. Voeg alleen nog niet gerenderde tabellen toe.
 const rendered=new Set();
 const collect=n=>{if(!n||rendered.has(nid(n)))return;rendered.add(nid(n));for(const c of children(n))collect(c)};
 for(const c of children(ar))collect(c);
 const fallback=inlineAt.filter(a=>!rendered.has(nid(a))).map(renderAttachment).join('');
 return `<article><div class="legalHead">${esc(label(ar))}</div>${ownText(ar)?`<div class="legalText">${renderInline(ar,ownText(ar))}</div>`:''}${renderIllustrations(ar)}<div class="legalChildren">${bodyChildren}${fallback}</div></article>`;
}
function renderArticleChild(n,ar,inlineIds=new Set()){if(['table','appendix'].includes(type(n))){if(inlineIds.has(nid(n)))return renderAttachment(n);if(isReliableAttachment(n))return'';return renderAttachment(n)}const no=num(n);const body=ownText(n);const childHtml=children(n).map(k=>renderArticleChild(k,ar,inlineIds)).join('');const content=body?renderInline(n,body):'';return `<div class="legalNode" data-content-node="${esc(nid(n))}">${no?`<div class="enumeration"><span class="enumNum">${esc(no)}</span><div>${content}${renderIllustrations(n)}</div></div>`:`<div class="legalText">${content}</div>${renderIllustrations(n)}`}${childHtml?`<div class="legalChildren">${childHtml}</div>`:''}</div>`}
function renderAttachment(a){if(type(a)==='table')return `<div class="attachmentBlock"><div class="sideTitle">${esc(label(a))}</div>${renderTable(a)}</div>`;if(type(a)==='appendix')return `<div class="attachmentBlock sideAppendix">${renderAppendixView(a)}</div>`;return `<div class="attachmentBlock"><div class="sideTitle">${esc(label(a))}</div><div class="legalText">${renderInline(a,ownText(a))}</div>${children(a).map(x=>renderArticleChild(x,articleOf(a))).join('')}</div>`}
function tableKey(t){return String(t?.regId||state.viewer.regulation||state.regulation)+':'+String(nid(t)||'table')}
function tableColumnCount(t){const cols=Array.isArray(t.columns)?t.columns:[];const rows=Array.isArray(t.rows)?t.rows:[];const declared=Number(t?.grid_columns||0);const rowWidth=Math.max(0,...rows.map(row=>(Array.isArray(row)?row:[]).reduce((sum,cell)=>sum+Math.max(1,Number((cell&&typeof cell==='object'?cell.colspan:1)||1)),0)));return Math.max(declared,cols.length,rowWidth)}
function tableMinWidth(t){const count=tableColumnCount(t);return count<2?0:Math.max(420,count*88)}
function tableColgroup(t){const cols=Array.isArray(t.columns)?t.columns:[],count=tableColumnCount(t);if(!count)return'';const stars=cols.map(c=>{const m=String(c?.colwidth||'').match(/^([0-9.]+)\*$/);return m?Number(m[1]):0}),sum=stars.reduce((a,b)=>a+b,0);return `<colgroup>${Array.from({length:count},(_,i)=>{const c=cols[i]||{},w=sum&&stars[i]?` style="width:${(stars[i]/sum*100).toFixed(4)}%"`:/^\d+(?:\.\d+)?(?:mm|cm|px|pt|%)$/.test(String(c.colwidth||''))?` style="width:${esc(c.colwidth)}"`:'';return `<col data-table-column="${i}"${w}>`}).join('')}</colgroup>`}
function tableCellClass(o){const a=String(o?.attrs?.align||'').toLowerCase(),v=String(o?.attrs?.valign||'').toLowerCase();return `${['left','right','center','justify'].includes(a)?' tableAlign-'+a:''}${['top','middle','bottom'].includes(v)?' tableValign-'+v:''}`}
function renderTable(t){const rows=Array.isArray(t.rows)?t.rows:[];if(!rows.length)return `<div class="legalText">${renderInline(t,ownText(t))}</div>`;const key=tableKey(t);return `<div class="tableWrap"><table class="legalTable" data-resizable-table data-table-key="${esc(key)}">${tableColgroup(t)}<tbody>${rows.map((r,ri)=>`<tr>${(Array.isArray(r)?r:[]).map((c,ci)=>{const o=typeof c==='object'&&c?c:{text:c};const rs=Number(o.rowspan||1),cs=Number(o.colspan||1),tag=o.header?'th':'td',cl=tableCellClass(o),handle=ri===0&&ci+cs<tableColumnCount(t)?`<span class="tableResizeHandle" data-table-resize="${ci}" title="Sleep om de kolombreedte aan te passen" aria-hidden="true"></span>`:'';return `<${tag}${rs>1?` rowspan="${rs}"`:''}${cs>1?` colspan="${cs}"`:''}${cl?` class="${cl.trim()}"`:''}>${renderInline(t,o.text??'')}${handle}</${tag}>`}).join('')}</tr>`).join('')}</tbody></table></div>`}
function bindTableResizers(root){root.querySelectorAll('table[data-resizable-table]').forEach(table=>{const cols=[...table.querySelectorAll('colgroup col')];if(cols.length<2)return;const key=table.dataset.tableKey||'';try{const saved=JSON.parse(localStorage.getItem('owz_table_widths:'+key)||'null');if(Array.isArray(saved)&&saved.length===cols.length)saved.forEach((w,i)=>cols[i].style.width=Math.max(70,Number(w)||70)+'px')}catch(_){}table.querySelectorAll('.tableResizeHandle').forEach(handle=>handle.addEventListener('mousedown',event=>{event.preventDefault();event.stopPropagation();const i=Number(handle.dataset.tableResize),next=cols[i+1];if(!cols[i]||!next)return;const widths=cols.map(col=>col.getBoundingClientRect().width);const start=event.clientX,left=widths[i],right=widths[i+1],total=widths.reduce((sum,w)=>sum+w,0);table.style.width=total+'px';document.body.classList.add('resizing');const move=e=>{const delta=e.clientX-start,a=Math.max(70,left+delta),b=Math.max(70,right-delta);if(a+b!==left+right)return;cols[i].style.width=a+'px';next.style.width=b+'px'};const up=()=>{document.removeEventListener('mousemove',move);document.removeEventListener('mouseup',up);document.body.classList.remove('resizing');try{localStorage.setItem('owz_table_widths:'+key,JSON.stringify(cols.map(col=>Math.round(col.getBoundingClientRect().width))))}catch(_){}};document.addEventListener('mousemove',move);document.addEventListener('mouseup',up)}))})}
function backReferencesFor(article){return state.backReferences.get(`${article.regId}:${nid(article)}`)||[]}
function renderBackReferences(article){const rows=backReferencesFor(article);if(!rows.length)return'';return `<section class="backReferences"><h3>Verwijzingen naar dit artikel</h3><p>Officiële vindplaatsen binnen de zes opgenomen regelingen.</p><ul>${rows.map((row,i)=>`<li><button class="legalLink backReferenceLink" data-back-reference="${i}"><strong>${esc(regName(row.regulation))}</strong> — ${esc(row.label)}</button>${row.anchor?`<span class="backReferenceAnchor">${esc(row.anchor)}</span>`:''}</li>`).join('')}</ul></section>`}
function renderBackReferenceFragment(source,row){const context=`${regName(row.regulation)} — ${row.label}`;if(type(source)==='table')return `<div class="sideReference"><div class="sideTitle">${esc(context)}</div><div class="sideContext">De tabel bevat de verwijzing: ${esc(row.anchor||'')}</div>${renderTable(source)}</div>`;if(type(source)==='article')return `<div class="sideReference">${renderArticle(source)}</div>`;const article=articleOf(source);return `<div class="sideReference"><div class="sideTitle">${esc(context)}</div><div class="sideContext">De gemarkeerde vindplaats bevat de verwijzing: ${esc(row.anchor||'')}</div>${renderArticleChild(source,article||source)}</div>`}
function publisherWebsite(text){const found=String(text||'').match(/(?:https?:\/\/|www\.)[^\s)<>,;]+/i);if(!found)return null;const shown=found[0].replace(/[.)]+$/,'');return {shown,url:/^https?:\/\//i.test(shown)?shown:`https://${shown}`}}
function renderNormValue(rec,cell,i){const heading=String((rec.headers||[])[i]||'').toLocaleLowerCase('nl-NL'),site=heading.includes('uitgever')&&publisherWebsite(cell);if(!site)return renderPlainInlineCore(rec.appendix,cell);const raw=String(cell||''),at=raw.indexOf(site.shown);return `${renderPlainInlineCore(rec.appendix,raw.slice(0,at))}<a class="publisherLink" href="${esc(site.url)}" target="_blank" rel="noopener noreferrer" title="Opent de website van de uitgever in een nieuw tabblad">${esc(site.shown)} <span aria-hidden="true">↗</span></a>${renderPlainInlineCore(rec.appendix,raw.slice(at+site.shown.length))}`}
function renderNormRecord(rec){const cells=rec.cells||[],headers=rec.headers||[];return `<section class="normRecord"><div class="sideContext">Norm uit Bijlage II van de Omgevingsregeling</div><h3>${esc(rec.norm)}</h3><dl>${cells.map((cell,i)=>`<div><dt>${esc(headers[i]||'Gegeven')}</dt><dd>${renderNormValue(rec,cell,i)}</dd></div>`).join('')}</dl></section>`}
function renderSide(){const box=$('side');const ar=state.side.article,selected=state.side.selected,reference=state.side.reference,row=state.side.referenceRow,norm=state.side.norm;if(norm){box.innerHTML=renderNormRecord(norm);bindInlineLinks(box);return}if(reference){box.innerHTML=`<button class="sideBack" data-back-reference-close>Terug naar verwijzingen</button><div class="sideContext">Verwijst naar ${esc(label(ar))}</div>${renderBackReferenceFragment(reference,row||{})}`;bindInlineLinks(box);bindTableResizers(box);return}if(selected&&['table','appendix'].includes(type(selected))){box.innerHTML=`${ar?`<div class="sideContext">Vanuit ${esc(label(ar))}</div>`:''}${renderAttachment(selected)}`;bindInlineLinks(box);bindTableResizers(box);return}if(!ar){box.innerHTML='<div class="empty">Bijlagen, gekoppelde tabellen en terugverwijzingen verschijnen hier.</div>';return}const at=articleAttachments(ar),refs=renderBackReferences(ar),registers=renderRegisterNotices(ar),context=contextualTableAttachments(ar).filter(x=>!at.some(a=>nid(a)===nid(x.attachment)));if(!at.length&&!refs&&!registers&&!context.length){box.innerHTML='<div class="empty">Geen gekoppelde tabellen, bijlagen of terugverwijzingen bij dit artikel.</div>';return}box.innerHTML=`<div class="sideTitle">${esc(label(ar))}</div>${registers}${refs}${at.map(renderAttachment).join('')}${context.map(x=>`<section class="contextAttachment"><div class="sideContext">Tabel uit aansturingsartikel ${esc(label(x.source))}</div>${renderAttachment(x.attachment)}</section>`).join('')}`;bindInlineLinks(box);bindTableResizers(box)}
const REF_RE=/\b(artikel|art\.?|paragraaf|afdeling|hoofdstuk|tabel|table|bijlage)\s+([0-9]+(?:\.[0-9]+)*[a-z]?|[IVXLCDM]+(?:[a-z]+)?)|§\s*([0-9]+(?:\.[0-9]+)*[a-z]?)/gi;
const REGULATION_ALIASES=[
 {reg:'OW',re:/\b(?:de\s+)?Omgevingswet\b/i},
 {reg:'BAL',re:/\b(?:het\s+)?Besluit\s+activiteiten\s+leefomgeving(?:\s*\(BAL\))?|\bBAL\b/i},
 {reg:'BBL',re:/\b(?:het\s+)?Besluit\s+bouwwerken\s+leefomgeving(?:\s*\(BBL\))?|\bBBL\b/i},
 {reg:'BKL',re:/\b(?:het\s+)?Besluit\s+kwaliteit\s+leefomgeving(?:\s*\(BKL\))?|\bBKL\b/i},
 {reg:'OB',re:/\b(?:het\s+)?Omgevingsbesluit(?:\s*\(OB\))?|\bOB\b/i},
 {reg:'OR',re:/\b(?:de\s+)?Omgevingsregeling(?:\s*\(OR\))?|\bOR\b/i}
];
const EXTERNAL_REGULATION_RE=/\b((?:Wet|Besluit|Regeling|Verordening|Richtlijn)\s+(?:(?![.;:\n]|\s+(?:en|of)\s+(?:artikel|paragraaf|hoofdstuk|afdeling)\b).){2,100})/gi;
function regulationMention(text){const raw=String(text||'');for(const x of REGULATION_ALIASES){const m=raw.match(x.re);if(m)return{reg:x.reg,name:regName(x.reg),match:m[0]}}return null}
function resolveRef(anchor,reg=state.regulation){const m=String(anchor).match(/^(artikel|art\.?|paragraaf|afdeling|hoofdstuk|tabel|table|bijlage)\s+(.+)$|^§\s*(.+)$/i);if(!m)return null;let k=(m[1]||'paragraaf').toLowerCase().replace('.',''),no=normNum(m[2]||m[3]);k=({artikel:'article',art:'article',paragraaf:'paragraph',afdeling:'section',hoofdstuk:'chapter',tabel:'table',table:'table',bijlage:'appendix'})[k]||k;return index(reg)?.byLegal.get(k+':'+no)||null}
function resolveCrossRegRef(anchor,context){const mention=regulationMention(context);if(!mention)return null;const target=resolveRef(anchor,mention.reg);return{...mention,target}}
function notImplemented(name){const dlg=$('notImplementedModal');$('notImplementedName').textContent=String(name||'Deze regeling');if(dlg)dlg.showModal();log('REGULATION_NOT_IMPLEMENTED',{name:String(name||'')})}
function openCrossReg(reg,target){if(!state.graphs.has(reg)){notImplemented(regName(reg));return}if(['table','appendix'].includes(type(target))){openAttachment(target);setStatus(`${regName(reg)} — ${label(target)} geopend in kolom 3. Zoekregeling in kolom 1 blijft ${regName(state.regulation)}.`);log('CROSS_REGULATION_ATTACHMENT_OPEN',{reg,id:nid(target),type:type(target),searchReg:state.regulation});return}state.search.active=false;$('resultCount').textContent='';state.viewer.trail.push(target);state.viewer.node=target;state.viewer.regulation=reg;state.viewer.overview=false;rememberViewerStep(target);syncSideForViewer(target);renderViewer();setStatus(`${regName(reg)} geopend in kolom 2: ${label(target)}. Zoekregeling in kolom 1 blijft ${regName(state.regulation)}.`);log('CROSS_REGULATION_OPEN',{reg,id:nid(target),type:type(target),searchReg:state.regulation})}
function glossary(){return index()?.glossary||[]}
function glossaryAppendixIds(){return new Set(glossary().map(x=>String(x.appendix_id||'')).filter(Boolean))}
function isGlossarySourceNode(n){if(!n)return false;const ids=glossaryAppendixIds();let cur=n,seen=new Set();while(cur&&!seen.has(nid(cur))){seen.add(nid(cur));if(ids.has(nid(cur)))return true;cur=node(parentId(cur),cur.regId)}return false}
function isGlossaryAppendix(n){return type(n)==='appendix'&&glossaryAppendixIds().has(nid(n))}
function renderGlossaryAppendix(){const terms=glossary().slice().sort((a,b)=>String(a.term).localeCompare(String(b.term),'nl',{sensitivity:'base'}));return `<div class="glossarySourceView"><div class="legalHead">Begrippenlijst</div><div class="glossarySourceMeta">${terms.length} begrippen — officiële begrippenbijlage van ${esc(regName(state.regulation))}</div><div class="glossarySourceList">${terms.map(x=>`<div class="glossarySourceItem"><span class="glossarySourceTerm">${esc(x.term)}:</span> <span class="glossarySourceDefinition">${esc(x.definition)}</span></div>`).join('')}</div></div>`}
function renderGlossaryText(source,text){
 const raw=String(text||'');
 if(isGlossarySourceNode(source))return esc(raw);
 const refs=Array.isArray(source?.glossary_refs)?new Set(source.glossary_refs.map(String)):null;
 const terms=refs?glossary().filter(x=>refs.has(String(x.key||x.term_normalized||x.term))):glossary();
 if(!terms.length)return esc(raw);
 const escaped=terms.map(x=>String(x.term).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));
 if(!escaped.length)return esc(raw);
 const re=new RegExp('(^|[^\\p{L}\\p{N}_])('+escaped.join('|')+')(?=$|[^\\p{L}\\p{N}_])','giu');
 let out='',last=0,m;
 while((m=re.exec(raw))){const start=m.index+m[1].length;out+=esc(raw.slice(last,start));const hit=m[2];const entry=terms.find(x=>String(x.term).toLocaleLowerCase('nl-NL')===hit.toLocaleLowerCase('nl-NL'));out+=esc(hit);if(entry)out+=`<button class="termInfo" data-term-info="${esc(entry.key||entry.term_normalized||entry.term)}" title="Toon begripsbepaling" aria-label="Begripsbepaling voor ${esc(hit)}"><span aria-hidden="true">i</span></button>`;last=start+hit.length;if(re.lastIndex<=m.index)re.lastIndex=m.index+1}
 return out+esc(raw.slice(last));
}
function glossaryEntry(key){return index()?.glossaryByKey?.get(String(key))||glossary().find(x=>String(x.key||x.term_normalized||x.term)===String(key))}
function hideTermHover(){document.querySelectorAll('.termHover').forEach(x=>x.remove())}
function showTermHover(key,anchor){const entry=glossaryEntry(key);if(!entry)return;hideTermHover();const tip=document.createElement('div');tip.className='termHover';tip.setAttribute('role','tooltip');tip.textContent=entry.definition;document.body.appendChild(tip);const r=anchor.getBoundingClientRect(),w=Math.min(420,window.innerWidth-20);tip.style.width=w+'px';tip.style.left=Math.max(10,Math.min(window.innerWidth-w-10,r.left))+'px';let top=r.bottom+6;if(top+tip.offsetHeight>window.innerHeight-10)top=Math.max(10,r.top-tip.offsetHeight-6);tip.style.top=top+'px'}
function showTermInfo(key){const entry=glossaryEntry(key);if(!entry)return;hideTermHover();$('termDialogTitle').textContent=entry.term;$('termDialogDefinition').textContent=entry.definition;$('termDefinitionModal').showModal();log('GLOSSARY_OPEN',{term:entry.term})}
function glossaryFor(reg){return index(reg)?.glossary||[]}
function renderGlossaryDialog(reg=state.glossaryRegulation||state.regulation){
 const dlg=$('glossaryModal'); if(!dlg)return;
 if(!state.graphs.has(reg))reg=state.regulation;
 state.glossaryRegulation=reg;
 const terms=glossaryFor(reg).slice().sort((a,b)=>String(a.term).localeCompare(String(b.term),'nl',{sensitivity:'base'}));
 $('glossaryTitle').textContent='Begrippenlijst per regeling';
 $('glossaryRegulations').innerHTML=REGS.map(r=>{const count=glossaryFor(r.id).length;const available=state.graphs.has(r.id);return `<button type="button" class="glossaryRegButton ${r.id===reg?'active':''}" data-glossary-reg="${esc(r.id)}" ${available?'':'disabled'}>${esc(r.id)} <span>${count}</span></button>`}).join('');
 $('glossaryMeta').textContent=terms.length?`${regName(reg)} — ${terms.length} begrippen uit de officiële bron van deze regeling.`:`${regName(reg)} — geen begrippen uit een begrippenbijlage in de gebouwde graph aangetroffen.`;
 const body=$('glossaryBody');
 body.innerHTML=terms.map((x,i)=>`<tr><td>${i+1}</td><td><strong>${esc(x.term)}</strong></td><td>${esc(x.definition)}</td></tr>`).join('')||'<tr><td colspan="3">Geen begrippen beschikbaar voor deze regeling.</td></tr>';
 $('glossaryRegulations').querySelectorAll('[data-glossary-reg]').forEach(b=>b.addEventListener('click',()=>{renderGlossaryDialog(b.dataset.glossaryReg);log('GLOSSARY_REGULATION_SELECT',{reg:b.dataset.glossaryReg,count:glossaryFor(b.dataset.glossaryReg).length})}));
}
function openGlossary(){
 state.glossaryRegulation=state.regulation;
 renderGlossaryDialog(state.regulation);
 const help=$('helpModal'); if(help?.open)help.close();
 $('glossaryModal').showModal();
 log('GLOSSARY_LIST_OPEN',{reg:state.regulation,count:glossaryFor(state.regulation).length});
}
const SEVESO_ANNEX_RE=/\bbijlage\s+[IVXLCDM]+(?:,\s*[^.;]*?)?\s+bij\s+de\s+Seveso-richtlijn\b/gi;
const SEVESO_URL='https://eur-lex.europa.eu/legal-content/NL/TXT/HTML/?uri=CELEX:32012L0018';
function renderNormText(source,text){const raw=String(text||'');if(isNormCatalogSource(source))return esc(raw);if(!state.normPattern)return renderGlossaryText(source,raw);state.normPattern.lastIndex=0;let out='',last=0,m;while((m=state.normPattern.exec(raw))){const start=m.index+m[1].length,hit=m[2],record=state.norms.get(normKey(hit));out+=renderGlossaryText(source,raw.slice(last,start));out+=record?`<button class="normLink" data-norm="${esc(record.key)}" title="Toon norm uit Bijlage II van de Omgevingsregeling">${esc(hit)}</button>`:renderGlossaryText(source,hit);last=start+hit.length;if(state.normPattern.lastIndex<=m.index)state.normPattern.lastIndex=m.index+1}return out+renderGlossaryText(source,raw.slice(last))}
function renderPlainInlineCore(source,text){let out='',last=0;const sourceArticle=articleOf(source),raw=String(text||''),sourceReg=source?.regId||state.viewer.regulation||state.regulation;REF_RE.lastIndex=0;for(const m of raw.matchAll(REF_RE)){out+=renderNormText(source,raw.slice(last,m.index));const context=raw.slice(Math.max(0,m.index-160),Math.min(raw.length,m.index+m[0].length+180));const cross=resolveCrossRegRef(m[0],context);const target=cross?.target||resolveRef(m[0],sourceReg);if(cross&&cross.reg!==sourceReg){if(target)out+=`<button class="legalLink" data-cross-reg="${esc(cross.reg)}" data-cross-id="${esc(nid(target))}">${esc(m[0])}</button>`;else if(state.graphs.has(cross.reg))out+=`<button class="legalLink" data-cross-reg-overview="${esc(cross.reg)}">${esc(m[0])}</button>`;else out+=renderNormText(source,m[0])}else if(target){const sameInlineTable=type(target)==='table'&&target.display_mode==='inline'&&sourceArticle&&String(target.article_id||'')===nid(sourceArticle);if(sameInlineTable){out+=`<button class="attachmentLink" data-inline="${esc(nid(target))}">${esc(m[0])}</button>`}else{const cls=['table','appendix'].includes(type(target))?'attachmentLink':'legalLink';out+=`<button class="${cls}" data-inline="${esc(nid(target))}">${esc(m[0])}</button>`}}else out+=renderNormText(source,m[0]);last=m.index+m[0].length}return out+renderNormText(source,raw.slice(last))}
function renderPlainInline(source,text){const raw=String(text||'');let out='',last=0;SEVESO_ANNEX_RE.lastIndex=0;for(const m of raw.matchAll(SEVESO_ANNEX_RE)){out+=renderPlainInlineCore(source,raw.slice(last,m.index));out+=`<a class="legalLink externalRef" href="${SEVESO_URL}" target="_blank" rel="noopener noreferrer" title="Opent in een nieuw tabblad">${esc(m[0])}</a>`;last=m.index+m[0].length}return out+renderPlainInlineCore(source,raw.slice(last))}
function externalMeta(ref){return state.externalRefs.get(String(ref?.bwb_id||ref?.doc||''))||null}
function externalLabel(ref,meta){const anchor=String(ref?.anchor||'').replace(/\s*\(BWBR\d+\)/gi,'').trim(),title=String(meta?.title||'');return title&&!anchor.toLocaleLowerCase('nl-NL').includes(title.toLocaleLowerCase('nl-NL'))?`${anchor} (${title})`:anchor}
function renderExternalRef(ref){const meta=externalMeta(ref),labelText=externalLabel(ref,meta),title=String(meta?.title||ref?.bwb_id||ref?.doc||'Externe verwijzing');const internal=REGS.find(r=>r.bwb===ref?.bwb_id);if(internal){const target=ref?.target||{},anchor=String(ref?.anchor||'').replace(/\s*\(BWBR\d+\)/gi,'').trim(),targetLabel=`${title}${target.number?`, artikel ${target.number}`:''}`;return `${esc(anchor)} <button class="internalRefInfo" data-external-reg="${esc(internal.id)}" data-external-type="${esc(target.type||'')}" data-external-no="${esc(target.number||'')}" title="Open ${esc(targetLabel)} in kolom 2" aria-label="Open ${esc(targetLabel)} in kolom 2">ⓘ</button>`}if(meta?.url)return `<a class="legalLink externalRef" href="${esc(meta.url)}" target="_blank" rel="noopener noreferrer" title="Opent in een nieuw tabblad">${esc(labelText)}</a>`;return `<button class="legalLink externalRef" data-external-unresolved="${esc(title)}" title="Externe verwijzing zonder openbare doelcode">${esc(labelText)}</button>`}
function renderInline(source,text){const raw=String(text||''),refs=Array.isArray(source?.external_refs)?source.external_refs:[];let out='',cursor=0;for(const ref of refs){const anchor=String(ref?.anchor||'');if(!anchor)continue;const at=raw.indexOf(anchor,cursor);if(at<0)continue;out+=renderPlainInline(source,raw.slice(cursor,at));out+=renderExternalRef(ref);cursor=at+anchor.length}return (out+renderPlainInline(source,raw.slice(cursor))).replace(/\n/g,'<br>')}
function openCrossRegOverview(reg){if(!state.graphs.has(reg)){notImplemented(regName(reg));return}state.search.active=false;$('resultCount').textContent='';const rs=roots(reg);const target=rs[0]||null;if(target){state.viewer.trail.push(target);state.viewer.node=target;state.viewer.regulation=reg;state.viewer.overview=true;rememberViewerStep(target)}else{state.viewer={...state.viewer,node:null,regulation:reg,overview:true}}clearSide();renderViewer();setStatus(`${regName(reg)} geopend in kolom 2. Zoekregeling in kolom 1 blijft ${regName(state.regulation)}.`);log('CROSS_REGULATION_OVERVIEW',{reg,searchReg:state.regulation})}
function openViewer(n){state.search.active=false;$('resultCount').textContent='';state.viewer.trail.push(n);state.viewer.node=n;state.viewer.regulation=n.regId||state.viewer.regulation||state.regulation;state.viewer.overview=false;rememberViewerStep(n);syncSideForViewer(n);renderViewer();log('VIEW_OPEN',{reg:state.viewer.regulation,id:nid(n),type:type(n)})}
function openSearchResult(i){const r=state.search.results[i];if(!r)return;const n=r.node;state.search.active=false;state.navigation.selected=n;expandPath(n);state.viewer={node:n,trail:ancestors(n),regulation:state.regulation,overview:false,history:[],historyIndex:-1};rememberViewerStep(n,true);syncSideForViewer(n);renderNavigation();renderViewer();setStatus(`Zoekresultaat geopend: ${label(n)}.`);log('SEARCH_RESULT_OPEN',{index:i,id:nid(n)})}
function openFavoriteResult(item){if(!item?.nodeId)return;if(item.reg&&state.graphs.has(item.reg)){$('regulationSelect').value=item.reg;chooseReg(item.reg)}const n=node(item.nodeId,item.reg||state.regulation);if(!n){setStatus('Dit favoriete resultaat is niet meer beschikbaar.');return}state.navigation.selected=n;expandPath(n);openViewer(n);renderNavigation();setStatus(`Favoriet geopend: ${label(n)}.`)}
function openAttachment(a){const linkedArticle=articleOf(a)||node(a.article_id,a.regId);const contextArticle=linkedArticle||articleOf(state.viewer.node)||null;state.side={article:contextArticle,selected:a,reference:null};renderSide();setStatus(`${label(a)} geopend in kolom 3.`);log('COLUMN3_ATTACHMENT_OPEN',{reg:a.regId||state.viewer.regulation,id:nid(a),type:type(a),article:contextArticle?nid(contextArticle):null})}
function openBackReference(i){const target=state.side.article,row=backReferencesFor(target)[Number(i)],source=row&&node(row.source_id||row.article_id,row.regulation);if(!target||!source)return;state.side={article:target,selected:null,reference:source,referenceRow:row};renderSide();setStatus(`${row.label} geopend in kolom 3.`);log('BACK_REFERENCE_OPEN',{target:nid(target),source:nid(source),reg:row.regulation,type:row.source_type||type(source)})}
function activateArticleAttachments(source){const ar=articleOf(source);if(!ar||type(source)==='article')return;state.side={article:ar,selected:null};renderSide();log('COLUMN3_OPEN',{article:nid(ar),source:nid(source)})}
function openExternalInternal(reg,kind,no){const target=kind&&no?index(reg)?.byLegal.get(String(kind)+':'+normNum(no)):null;if(target)openCrossReg(reg,target);else openCrossRegOverview(reg);log('EXTERNAL_REFERENCE_OPEN',{reg,kind,no,target:target?nid(target):null})}
function hideNormHover(){document.querySelectorAll('.normHover').forEach(x=>x.remove())}
function showNormHover(key,anchor){const rec=state.norms.get(String(key));if(!rec)return;hideNormHover();const tip=document.createElement('div');tip.className='normHover';tip.setAttribute('role','tooltip');tip.innerHTML=`<strong>${esc(rec.norm)}</strong>${rec.cells.slice(1).map((cell,i)=>`<span><b>${esc(rec.headers[i+1]||'')}</b>${esc(cell)}</span>`).join('')}`;document.body.appendChild(tip);const r=anchor.getBoundingClientRect(),w=Math.min(520,window.innerWidth-20);tip.style.width=w+'px';tip.style.left=Math.max(10,Math.min(window.innerWidth-w-10,r.left))+'px';let top=r.bottom+6;if(top+tip.offsetHeight>window.innerHeight-10)top=Math.max(10,r.top-tip.offsetHeight-6);tip.style.top=top+'px'}
function openNorm(key,source){const rec=state.norms.get(String(key));if(!rec)return;state.side={article:articleOf(source)||null,selected:null,reference:null,norm:rec};hideNormHover();renderSide();setStatus(`${rec.norm} uit Bijlage II van de Omgevingsregeling geopend in kolom 3.`);log('NORM_REFERENCE_OPEN',{norm:rec.norm})}
function bindInlineLinks(root){root.querySelectorAll('[data-norm]').forEach(b=>{b.addEventListener('click',e=>{e.stopPropagation();openNorm(b.dataset.norm,root.id==='side'?state.side.article:state.viewer.node)});b.addEventListener('mouseenter',()=>showNormHover(b.dataset.norm,b));b.addEventListener('mouseleave',hideNormHover)});root.querySelectorAll('[data-inline]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const linkReg=(root.id==='side'&&(state.side.selected?.regId||state.side.reference?.regId))?(state.side.selected?.regId||state.side.reference?.regId):(state.viewer.regulation||state.regulation);const t=node(b.dataset.inline,linkReg);if(!t)return;if(['table','appendix'].includes(type(t)))openAttachment(t);else openViewer(t)}));root.querySelectorAll('[data-back-reference]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();openBackReference(b.dataset.backReference)}));root.querySelectorAll('[data-back-reference-close]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();state.side={article:state.side.article,selected:null,reference:null,referenceRow:null};renderSide()}));root.querySelectorAll('[data-cross-reg]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const reg=b.dataset.crossReg,t=node(b.dataset.crossId,reg);if(t)openCrossReg(reg,t);else if(state.graphs.has(reg))openCrossRegOverview(reg);else notImplemented(regName(reg))}));root.querySelectorAll('[data-cross-reg-overview]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();openCrossRegOverview(b.dataset.crossRegOverview)}));root.querySelectorAll('[data-external-reg]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();openExternalInternal(b.dataset.externalReg,b.dataset.externalType,b.dataset.externalNo)}));root.querySelectorAll('[data-external-unresolved]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();notImplemented(b.dataset.externalUnresolved)}));root.querySelectorAll('[data-regulation-info]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();notImplemented(b.dataset.regulationInfo)}))}
async function executeSearch(){if(state.searchBusy)return;state.viewer.regulation=state.regulation;const q=String($('searchInput').value||'').trim();if(q.length<2)return;state.searchBusy=true;$('searchButton').disabled=true;closeHistory();setStatus(`Zoeken naar “${q}”…`);await new Promise(resolve=>requestAnimationFrame(resolve));try{const results=search(q);state.search={query:q,results,active:true};saveHistory(q);renderViewer();updateStar();setStatus(`${results.length} zoekresultaten voor “${q}” in ${state.regulation}.`);log('SEARCH',{query:q,count:results.length,reg:state.regulation})}finally{state.searchBusy=false;$('searchButton').disabled=String($('searchInput').value||'').trim().length<2}}
function chooseReg(reg){reg=validRegulation(reg);if(!state.graphs.has(reg)){setStatus(`${regName(reg)} wordt nog geladen.`);return}$('regulationSelect').value=reg;state.regulation=reg;state.search={query:'',results:[],active:false};state.navigation={selected:null,expanded:new Set()};state.viewer={node:null,trail:[],regulation:reg,history:[],historyIndex:-1};state.side={article:null,selected:null};$('searchInput').value='';$('searchButton').disabled=true;$('resultCount').textContent='';$('searchInput').placeholder=`Zoek in ${regName(reg)}…`;updateStar();renderNavigation();renderViewer();renderSide();renderRegulationInfo();setRegulationInfoVisible(false);setStatus(`Startregeling: ${regName(reg)}.`)}
function setupEvents(){$('searchInput').addEventListener('input',()=>{$('searchButton').disabled=state.searchBusy||$('searchInput').value.trim().length<2;updateStar()});$('searchInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();executeSearch()}});$('searchButton').addEventListener('click',executeSearch);$('favoriteQueryButton').addEventListener('click',toggleQueryFavorite);$('regulationSelect').addEventListener('change',e=>chooseReg(e.target.value));let regulationInfoPinned=false;const regulationPicker=$('regulationPicker');$('regulationInfoButton').addEventListener('click',e=>{e.stopPropagation();regulationInfoPinned=$('regulationInfoTooltip').hidden;setRegulationInfoVisible(regulationInfoPinned)});regulationPicker.addEventListener('mouseenter',()=>setRegulationInfoVisible(true));regulationPicker.addEventListener('mouseleave',()=>{if(!regulationInfoPinned)setRegulationInfoVisible(false)});$('regulationInfoButton').addEventListener('focus',()=>setRegulationInfoVisible(true));$('regulationInfoButton').addEventListener('blur',()=>{setTimeout(()=>{if(!regulationInfoPinned&&!regulationPicker.contains(document.activeElement))setRegulationInfoVisible(false)},120)});document.addEventListener('click',e=>{if(!regulationPicker.contains(e.target)){regulationInfoPinned=false;setRegulationInfoVisible(false)}});$('explanatoryNotesButton').addEventListener('click',()=>window.open(`nvt.html?regeling=${encodeURIComponent(state.regulation)}`,'_blank','noopener'));$('rulesOnMapButton').addEventListener('click',()=>window.open('https://omgevingswet.overheid.nl/regels-op-de-kaart/zoeken/locatie','_blank','noopener'));$('viewerBack').addEventListener('click',()=>moveViewerHistory(-1));$('viewerForward').addEventListener('click',()=>moveViewerHistory(1));$('viewerReset').addEventListener('click',()=>{const start='BAL';chooseReg(start);setStatus(`Terug naar ${regName(start)}. Kolom 2 en 3 zijn leeggemaakt.`);log('VIEWER_HISTORY_RESET',{reg:start})});
 $('recentTab').addEventListener('click',()=>{state.historyTab='recent';$('recentTab').classList.add('active');$('favoritesTab').classList.remove('active');renderHistory()});$('favoritesTab').addEventListener('click',()=>{state.historyTab='favorites';$('favoritesTab').classList.add('active');$('recentTab').classList.remove('active');renderHistory()});
 $('historyPanel').addEventListener('click',e=>{const b=e.target.closest('[data-history]');if(!b)return;const data=state.historyTab==='favorites'?favorites():history(),x=data[Number(b.dataset.history)];if(!x)return;if(x.kind==='result'){openFavoriteResult(x);closeHistory();return}if(x.reg&&state.graphs.has(x.reg)){$('regulationSelect').value=x.reg;chooseReg(x.reg)}$('searchInput').value=x.query||'';$('searchButton').disabled=String(x.query||'').trim().length<2;updateStar();executeSearch()});
 $('navigation').addEventListener('click',e=>{const b=e.target.closest('[data-nav]');if(b){const n=node(b.dataset.nav,state.regulation);if(n)selectNavigation(n)}});$('viewer').addEventListener('click',e=>{const favorite=e.target.closest('[data-result-favorite]');if(favorite){e.stopPropagation();toggleResultFavorite(Number(favorite.dataset.resultFavorite));return}const back=e.target.closest('[data-view-back]');if(back){moveViewerHistory(-1);return}const forward=e.target.closest('[data-view-forward]');if(forward){moveViewerHistory(1);return}const rc=e.target.closest('[data-result-crumb]');if(rc){openSearchBreadcrumbNode(node(rc.dataset.resultCrumb));return}const rr=e.target.closest('[data-result-reg]');if(rr){openSearchRegulation();return}const r=e.target.closest('[data-result]');if(r){openSearchResult(Number(r.dataset.result));return}const c=e.target.closest('[data-crumb]');if(c){const i=Number(c.dataset.crumb),n=state.viewer.trail[i];if(n){state.viewer.trail=state.viewer.trail.slice(0,i+1);state.viewer.node=n;state.viewer.regulation=n.regId||state.regulation;rememberViewerStep(n);clearSide();renderViewer()}return}const ti=e.target.closest('[data-term-info]');if(ti){showTermInfo(ti.dataset.termInfo);return}const v=e.target.closest('[data-view-node]');if(v){const n=node(v.dataset.viewNode);if(n)openViewer(n);return}const content=e.target.closest('[data-content-node]');if(content){const n=node(content.dataset.contentNode);if(n)activateArticleAttachments(n)}});
 $('viewer').addEventListener('mouseover',e=>{const ti=e.target.closest('[data-term-info]');if(ti&&!ti.contains(e.relatedTarget))showTermHover(ti.dataset.termInfo,ti)});$('viewer').addEventListener('mouseout',e=>{const ti=e.target.closest('[data-term-info]');if(ti&&!ti.contains(e.relatedTarget))hideTermHover()});
 $('collapseButton').addEventListener('click',()=>{state.navigation.expanded.clear();renderNavigation();setStatus('Navigatie teruggevouwen tot hoofdstukniveau.')});$('homeButton').addEventListener('click',()=>chooseReg(state.regulation));$('commentsButton').addEventListener('click',()=>openComments());$('commentHistoryButton').addEventListener('click',()=>openComments($('commentHistoryButton').dataset.commentMode||'history'));$('newCommentButton').addEventListener('click',()=>{$('commentsModal').close();$('commentError').textContent='';$('commentModal').showModal();$('commentMessage').focus()});$('cancelComment').addEventListener('click',()=>$('commentModal').close());$('commentForm').addEventListener('submit',submitComment);$('settingsButton').addEventListener('click',()=>{$('historyLimit').value=localStorage.getItem('owz_history_limit')||'10';$('settingsModal').showModal()});$('aboutButton').addEventListener('click',()=>$('aboutModal').showModal());$('clearHistory').addEventListener('click',()=>{localStorage.removeItem('owz_history');renderHistory()});$('clearFavorites').addEventListener('click',()=>{localStorage.removeItem('owz_favorites');updateStar();renderHistory()});$('historyLimit').addEventListener('change',e=>localStorage.setItem('owz_history_limit',String(Math.max(1,Number(e.target.value)||10))));
 setupResize();document.addEventListener('click',e=>{if(!e.target.closest('.searchbar'))closeHistory()});window.addEventListener('beforeunload',()=>{if(logQueue.length)navigator.sendBeacon('/ui-log',new Blob([JSON.stringify({session:'v550-unload',entries:logQueue})],{type:'application/json'}))})}
function setupResize(){let mode=null,start=0,w=0;document.querySelectorAll('.resizer').forEach(h=>h.addEventListener('mousedown',e=>{mode=h.dataset.resize;start=e.clientX;w=(mode==='nav'?$('navigationPanel'):$('viewerPanel')).getBoundingClientRect().width;document.body.classList.add('resizing');e.preventDefault()}));document.addEventListener('mousemove',e=>{if(!mode)return;const el=mode==='nav'?$('navigationPanel'):$('viewerPanel');el.style.width=Math.max(mode==='nav'?180:280,w+e.clientX-start)+'px'});document.addEventListener('mouseup',()=>{mode=null;document.body.classList.remove('resizing')})}
async function loadExternalRefs(){try{const res=await fetch('data/external_refs.json',{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);const data=await res.json();for(const ref of data.references||[])state.externalRefs.set(String(ref.key),ref);log('EXTERNAL_REFERENCES_LOADED',{count:state.externalRefs.size})}catch(e){log('EXTERNAL_REFERENCES_FAILED',{error:e.message})}}
async function loadBackReferences(){try{const res=await fetch('data/back_references.json',{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);const data=await res.json();for(const [key,rows] of Object.entries(data.references||{}))state.backReferences.set(key,rows);log('BACK_REFERENCES_LOADED',{count:data.count||0})}catch(e){log('BACK_REFERENCES_FAILED',{error:e.message})}}
function formatVersionDate(value){const m=String(value||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}-${m[2]}-${m[1]}`:'onbekend'}
function regulationOption(r){return `<option value="${r.id}">${esc(r.name)} — bron: ${esc(formatVersionDate(state.versions?.[r.id]?.imported_on))}</option>`}
function regulationInfoHtml(reg){const info=state.versions?.[reg]||{};return `<strong>${esc(regName(reg))}</strong><span>Bron gedownload: ${esc(formatVersionDate(info.imported_on))}</span><span>Laatste officiële versie: ${esc(formatVersionDate(info.official_version_date))}</span><span class="regulationInfoSource">Gegevens uit de officiële KOOP/BWB-bron.</span>`}
function renderRegulationInfo(){const tooltip=$('regulationInfoTooltip');if(!tooltip)return;tooltip.innerHTML=regulationInfoHtml(state.regulation||$('regulationSelect').value)}
function setRegulationInfoVisible(visible){const tooltip=$('regulationInfoTooltip'),button=$('regulationInfoButton');if(!tooltip||!button)return;tooltip.hidden=!visible;button.setAttribute('aria-expanded',String(visible))}

async function loadRegulationVersions(){try{const res=await fetch('data/regulation_versions.json',{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);const data=await res.json();state.versions=data.regulations||{};log('REGULATION_VERSIONS_LOADED')}catch(e){state.versions={};log('REGULATION_VERSIONS_FAILED',{error:e.message})}}
async function load(){const input=$('searchInput'),searchButton=$('searchButton'),favoriteButton=$('favoriteQueryButton');input.disabled=true;searchButton.disabled=true;favoriteButton.disabled=true;input.placeholder='Regelingen laden…';$('regulationSelect').disabled=true;setStatus('Regelingen laden…');await Promise.all([loadExternalRefs(),loadBackReferences(),loadRegulationVersions()]);const opts=REGS.map(regulationOption).join('');$('regulationSelect').innerHTML=opts;const outcomes=await Promise.all(REGS.map(async r=>{try{const res=await fetch('data/graph/'+r.file,{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);const g=await res.json();state.graphs.set(r.id,g);buildIndex(r.id,g);log('GRAPH_LOADED',{reg:r.id,nodes:g.nodes?.length||0});return true}catch(e){log('GRAPH_FAILED',{reg:r.id,error:e.message});return false}}));buildNormIndex();buildRegisterIndex();let def='BAL';if(!state.graphs.has(def))def=REGS.find(r=>state.graphs.has(r.id))?.id||'BAL';prepareSearchIndex(def);$('regulationSelect').disabled=false;input.disabled=false;favoriteButton.disabled=false;chooseReg(def);setStatus(`${outcomes.filter(Boolean).length}/6 regelingen geladen. ${regName(def)} is actief.`)}
registerSiteVisit();setupEvents();renderSide();load().catch(e=>{setStatus('Fout bij laden: '+e.message);log('LOAD_FATAL',{error:e.message})});
})();
