import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const SUPABASE_URL='https://lemcbncvqcsffatsxpdq.supabase.co';
const SUPABASE_KEY='sb_publishable_Lo6PkEOT4z5GgLRgkDrx4Q_5O0Y0PsB';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);
let factorId='',activeTab='comments';
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const msg=(id,text,fail=false)=>{const node=$(id);node.textContent=text;node.classList.toggle('error',fail)};
function show(id,visible=true){$(id).hidden=!visible}

async function requestEmailCode(event){event.preventDefault();const email=$('email').value.trim();const {error}=await supabase.auth.signInWithOtp({email,options:{shouldCreateUser:false}});msg('loginMessage',error?'De code kon niet worden verstuurd. Controleer het e-mailadres of vraag toegang.':'De inlogcode is verstuurd. Controleer uw e-mail.',Boolean(error));if(!error)show('codeForm')}
async function verifyEmailCode(event){event.preventDefault();const email=$('email').value.trim(),token=$('emailCode').value.trim();const {error}=await supabase.auth.verifyOtp({email,token,type:'email'});if(error){msg('loginMessage','De e-mailcode is onjuist of verlopen.',true);return}await continueLogin()}
async function continueLogin(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:admin}=await supabase.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();if(!admin){msg('loginMessage','Dit account heeft nog geen beheerrechten. Vraag een bestaande beheerder om toegang.',true);return}const {data:aal}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();show('adminLogin',false);if(aal.nextLevel==='aal2'&&aal.currentLevel!=='aal2'){const {data:factors}=await supabase.auth.mfa.listFactors();factorId=factors.totp.find(item=>item.status==='verified')?.id||'';show('mfaChallenge');return}if(aal.currentLevel==='aal1'){show('mfaSetup');return}await openWorkspace(user)}
async function enroll(event){event.preventDefault();const {data,error}=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'Omgevingswet Zoeker test'});if(error){msg('mfaMessage','De authenticator kon niet worden voorbereid.',true);return}factorId=data.id;$('mfaQr').src=`data:image/svg+xml;utf8,${encodeURIComponent(data.totp.qr_code)}`;$('mfaQr').hidden=false;$('mfaSecret').textContent=`Handmatig invoeren: ${data.totp.secret}`;$('mfaSecret').hidden=false;show('mfaVerifyForm');msg('mfaMessage','Scan de QR-code en voer de actuele code in.')}
async function verifyEnrollment(event){event.preventDefault();const {data:challenge,error:challengeError}=await supabase.auth.mfa.challenge({factorId});if(challengeError){msg('mfaMessage','De controle kon niet worden gestart.',true);return}const {error}=await supabase.auth.mfa.verify({factorId,challengeId:challenge.id,code:$('mfaCode').value.trim()});if(error){msg('mfaMessage','De code klopt niet. Probeer de actuele code.',true);return}const {data:{user}}=await supabase.auth.getUser();show('mfaSetup',false);await openWorkspace(user)}
async function verifyChallenge(event){event.preventDefault();const {data:challenge,error:challengeError}=await supabase.auth.mfa.challenge({factorId});if(challengeError){msg('challengeMessage','De controle kon niet worden gestart.',true);return}const {error}=await supabase.auth.mfa.verify({factorId,challengeId:challenge.id,code:$('challengeCode').value.trim()});if(error){msg('challengeMessage','De code klopt niet. Probeer de actuele code.',true);return}const {data:{user}}=await supabase.auth.getUser();show('mfaChallenge',false);await openWorkspace(user)}
async function openWorkspace(user){show('adminWorkspace');$('adminIdentity').textContent=user.email;await loadTab(activeTab)}
async function loadTab(tab){activeTab=tab;document.querySelectorAll('[data-admin-tab]').forEach(button=>button.classList.toggle('active',button.dataset.adminTab===tab));const box=$('adminContent');box.innerHTML='<p>Gegevens laden…</p>';if(tab==='comments'){const {data,error}=await supabase.from('comments').select('*').order('created_at',{ascending:false});box.innerHTML=error?'<p>Opmerkingen zijn niet beschikbaar.</p>':`<table><thead><tr><th>Datum</th><th>Opmerking</th><th>Status</th><th>Reactie ontwikkelaar</th></tr></thead><tbody>${data.map(row=>`<tr><td>${esc(new Date(row.created_at).toLocaleDateString('nl-NL'))}</td><td>${esc(row.message)}</td><td>${esc(row.status)}</td><td>${esc(row.reactie||'')}</td></tr>`).join('')}</tbody></table>`;return}if(tab==='statuses'){const {data,error}=await supabase.from('statuses').select('*').order('table_name').order('sort_order');box.innerHTML=error?'<p>Statussen zijn niet beschikbaar.</p>':`<table><thead><tr><th>Tabel</th><th>Status</th><th>Omschrijving</th><th>Actief</th></tr></thead><tbody>${data.map(row=>`<tr><td>${esc(row.table_name)}</td><td>${esc(row.status)}</td><td>${esc(row.description||'')}</td><td>${row.is_active?'Ja':'Nee'}</td></tr>`).join('')}</tbody></table>`;return}if(tab==='qna'){const {data,error}=await supabase.from('qna').select('*').order('rubriek').order('volgorde');box.innerHTML=error?'<p>Q&A is niet beschikbaar.</p>':`<table><thead><tr><th>Rubriek</th><th>Vraag</th><th>Zichtbaar</th></tr></thead><tbody>${data.map(row=>`<tr><td>${esc(row.rubriek)}</td><td>${esc(row.vraag)}</td><td>${row.zichtbaar?'Ja':'Nee'}</td></tr>`).join('')}</tbody></table>`;return}if(tab==='releases'){const {data,error}=await supabase.from('releases').select('*').order('published_at',{ascending:false});box.innerHTML=error?'<p>Versies zijn niet beschikbaar.</p>':`<table><thead><tr><th>Versie</th><th>Soort</th><th>Gepubliceerd</th></tr></thead><tbody>${data.map(row=>`<tr><td>${esc(row.version)}</td><td>${esc(row.release_kind)}</td><td>${esc(new Date(row.published_at).toLocaleString('nl-NL'))}</td></tr>`).join('')}</tbody></table>`;return}const [{data:weekly},{data:monthly}]=await Promise.all([supabase.from('site_visit_weekly').select('*'),supabase.from('site_visit_monthly').select('*')]);box.innerHTML=`<h3>Per week</h3>${visitTable(weekly)}<h3>Per maand</h3>${visitTable(monthly)}`}
function visitTable(rows=[]){return `<table><thead><tr><th>Periode</th><th>Bezoeken</th><th>Unieke bezoeken</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${esc(row.periode_start)}</td><td>${esc(row.bezoeken)}</td><td>${esc(row.unieke_bezoeken)}</td></tr>`).join('')}</tbody></table>`}
$('emailForm').addEventListener('submit',requestEmailCode);$('codeForm').addEventListener('submit',verifyEmailCode);$('mfaEnrollForm').addEventListener('submit',enroll);$('mfaVerifyForm').addEventListener('submit',verifyEnrollment);$('mfaChallengeForm').addEventListener('submit',verifyChallenge);$('signOut').addEventListener('click',async()=>{await supabase.auth.signOut();location.reload()});document.querySelectorAll('[data-admin-tab]').forEach(button=>button.addEventListener('click',()=>loadTab(button.dataset.adminTab)));supabase.auth.getSession().then(({data:{session}})=>session&&continueLogin());
