create table if not exists public.qna (
  id bigint generated by default as identity primary key,
  rubriek text not null,
  vraag text not null unique,
  antwoord text not null,
  zichtbaar boolean not null default true,
  volgorde integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.qna enable row level security;

drop policy if exists "Zichtbare Q&A zijn openbaar leesbaar" on public.qna;
create policy "Zichtbare Q&A zijn openbaar leesbaar"
  on public.qna for select using (zichtbaar = true);

insert into public.qna (rubriek, vraag, antwoord, zichtbaar, volgorde) values
  ('Zoeken', 'Hoe zoek ik naar een onderwerp of artikel?', 'Kies eerst een regeling. Typ daarna minimaal twee tekens, een begrip of een artikelnummer. Druk op Enter of klik op Zoeken.', true, 10),
  ('Zoeken', 'Kan ik zonder zoekwoord door een regeling bladeren?', 'Ja. Open in kolom 1 een hoofdstuk, afdeling of paragraaf. Klik op een artikel om de tekst in kolom 2 te lezen.', true, 20),
  ('Zoeken', 'Wat zijn favorieten en recente zoekopdrachten?', 'Met de ster bewaart u een zoekopdracht als favoriet. Bij recente zoekopdrachten en favorieten wordt de zoekopdracht direct uitgevoerd.', true, 30),
  ('Navigatie', 'Wat betekenen de drie kolommen?', 'Kolom 1 bevat de opbouw van de regeling. Kolom 2 toont de geselecteerde tekst. Kolom 3 toont bijlagen, tabellen, begrippen en terugverwijzingen.', true, 10),
  ('Navigatie', 'Hoe ga ik terug naar een eerder bekeken tekst?', 'Gebruik de pijlen boven kolom 2. Het getal ernaast laat zien op welke plaats u zich in de klikgeschiedenis bevindt. Reset leegt kolom 2 en 3 en gaat terug naar de beginregeling.', true, 20),
  ('Navigatie', 'Wat doet Klap alles in?', 'Hiermee vouwt de navigatie terug tot hoofdstukniveau. De kleinere tekst onder een ingeklapt onderdeel geeft een vooruitblik op de inhoud.', true, 30),
  ('Tekst en verwijzingen', 'Waarom zijn woorden blauw?', 'Blauwe tekst is een juridische verwijzing. Een verwijzing binnen de zes opgenomen regelingen opent in kolom 2. Aanpalende Nederlandse regelgeving opent in een apart tabblad op Wetten.nl. Europese regelgeving opent in een apart tabblad op EUR-Lex. In die externe tabbladen zijn geen aanvullende zoekfuncties van Omgevingswet Zoeker beschikbaar.', true, 10),
  ('Tekst en verwijzingen', 'Waarom zie ik soms een tabel of bijlage in kolom 3?', 'Een artikel kan verwijzen naar een tabel, bijlage of begripsbepaling. Die verschijnt dan naast de tekst, zodat het oorspronkelijke artikel zichtbaar blijft.', true, 20),
  ('Tekst en verwijzingen', 'Wat betekenen terugverwijzingen?', 'Kolom 3 kan laten zien welke artikelen uit de andere opgenomen regelingen naar het geselecteerde artikel verwijzen. Zo wordt zichtbaar waar een bepaling elders doorwerkt.', true, 30),
  ('Actualiteit', 'Hoe actueel zijn de regelingen?', 'De website bouwt dagelijks opnieuw met de officiële KOOP/BWB-bronnen. Alleen wanneer de inhoud verandert, wordt een nieuwe versie gepubliceerd. De teksten zijn actueel op de dag van de laatste geslaagde import. [[VERSIES]]', true, 10),
  ('Actualiteit', 'Blijft de website werken wanneer de Wettenbank niet bereikbaar is?', 'Ja. De gepubliceerde Omgevingswet Zoeker bevat een eigen, statische kopie van de zes opgenomen regelingen. Zoeken, navigeren en lezen blijven daarom werken. Alleen een dagelijkse actualisatie kan dan niet worden uitgevoerd. De website blijft in dat geval de laatst succesvol gepubliceerde versie tonen. Ook externe verwijzingen naar Wetten.nl zijn tijdelijk niet beschikbaar zolang die website niet bereikbaar is. [[VERSIES]]', true, 20),
  ('Actualiteit', 'Wat is de officiële bron?', 'De bron is steeds de officiële KOOP/BWB-tekst. Controleer bij formeel juridisch gebruik altijd ook de officiële publicatie en de geldende datum.', true, 30)
on conflict (vraag) do update set
  rubriek = excluded.rubriek,
  antwoord = excluded.antwoord,
  zichtbaar = excluded.zichtbaar,
  volgorde = excluded.volgorde,
  updated_at = now();
