-- Algemene statussen.  Elke tabel krijgt een eigen set via table_name.
create table if not exists public.statuses (
  id bigint generated by default as identity primary key,
  table_name text not null,
  code text not null,
  status text not null,
  description text,
  color text,
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (table_name, code),
  unique (table_name, status),
  unique (table_name, id)
);

insert into public.statuses (table_name, code, status, description, color, sort_order)
values
  ('comments', 'ontvangen', 'Ontvangen', 'De opmerking is ontvangen en wacht op beoordeling.', '#2563eb', 10),
  ('comments', 'in_onderzoek', 'In onderzoek', 'De opmerking wordt onderzocht.', '#f59e0b', 20),
  ('comments', 'geaccepteerd', 'Geaccepteerd', 'De wijziging is geaccepteerd voor uitvoering.', '#86efac', 30),
  ('comments', 'doorgevoerd', 'Doorgevoerd', 'De wijziging is opgenomen in een versie.', '#15803d', 40),
  ('comments', 'niet_geaccepteerd', 'Niet geaccepteerd', 'De wijziging wordt niet uitgevoerd.', '#dc2626', 50)
on conflict (table_name, code) do update set
  status = excluded.status,
  description = excluded.description,
  color = excluded.color,
  sort_order = excluded.sort_order,
  updated_at = now();

create or replace function public.default_comment_status()
returns bigint language sql stable as $$
  select id from public.statuses
  where table_name = 'comments' and code = 'ontvangen'
  limit 1;
$$;

alter table public.comments
  add column if not exists status_scope text not null default 'comments',
  add column if not exists status_id bigint;

update public.comments c
set status_id = s.id
from public.statuses s
where s.table_name = 'comments'
  and s.status = c.status
  and c.status_id is null;

alter table public.comments
  alter column status_id set default public.default_comment_status(),
  alter column status_id set not null;

-- De oude tekstcontrole zou nieuwe statuswaarden buiten deze opzoektabel blokkeren.
alter table public.comments drop constraint if exists comments_status_check;

alter table public.comments drop constraint if exists comments_status_lookup_fkey;
alter table public.comments add constraint comments_status_lookup_fkey
  foreign key (status_scope, status_id)
  references public.statuses (table_name, id);

create or replace function public.sync_comment_status()
returns trigger language plpgsql as $$
begin
  select status into new.status
  from public.statuses
  where id = new.status_id and table_name = new.status_scope;
  return new;
end;
$$;

drop trigger if exists comments_status_sync on public.comments;
create trigger comments_status_sync
before insert or update on public.comments
for each row execute function public.sync_comment_status();

alter table public.statuses enable row level security;
drop policy if exists status_read_active on public.statuses;
create policy status_read_active on public.statuses
for select using (is_active);
